// DANH MỤC THỦ TỤC HÀNH CHÍNH THUỘC THẨM QUYỀN GIẢI QUYẾT CỦA UBND XÃ ĐĂK PXI - NĂM 2026

export const FIELD_GROUPS = [
  { id: "dat-dai-lam-nghiep", name: "Đất đai - Lâm nghiệp" },
  { id: "ho-tich-tu-phap", name: "Tư pháp - Hộ tịch" },
  { id: "giao-duc-dao-tao", name: "Giáo dục - Đào tạo" },
  { id: "nguoi-co-cong", name: "Người có công" },
  { id: "bao-tro-xa-hoi", name: "Bảo trợ xã hội - Lao động" },
  { id: "giao-thong-van-tai", name: "Giao thông - Vận tải" },
  { id: "thuy-loi-moi-truong", name: "Thủy lợi - Môi trường - Nước" },
  { id: "nong-nghiep-thuy-san", name: "Nông nghiệp - Thủy sản" },
  { id: "kinh-te-doanh-nghiep", name: "Kinh tế - Hộ kinh doanh" },
  { id: "van-hoa-ton-giao", name: "Văn hóa - Tôn giáo - Hội" },
  { id: "xay-dung-quy-hoach", name: "Xây dựng - Quy hoạch" },
  { id: "linh-vuc-khac", name: "Lĩnh vực khác" }
];

const RAW_PROCEDURES_2026 = [
  { stt: 1, code: "1.000080.01", title: "Thủ tục đăng ký nhận cha, mẹ, con có yếu tố nước ngoài tại khu vực biên giới", type: "toan-trinh", group: "ho-tich-tu-phap" },
  { stt: 2, code: "1.000094.01", title: "Thủ tục đăng ký kết hôn có yếu tố nước ngoài tại khu vực biên giới", type: "toan-trinh", group: "ho-tich-tu-phap" },
  { stt: 3, code: "1.000110.01", title: "Thủ tục đăng ký khai sinh có yếu tố nước ngoài tại khu vực biên giới", type: "toan-trinh", group: "ho-tich-tu-phap" },
  { stt: 4, code: "1.000280.01", title: "Công nhận trường tiểu học đạt chuẩn quốc gia", type: "toan-trinh", group: "giao-duc-dao-tao" },
  { stt: 5, code: "1.000288.01", title: "Công nhận trường mầm non đạt chuẩn Quốc gia", type: "toan-trinh", group: "giao-duc-dao-tao" },
  { stt: 6, code: "1.000314.01", title: "Chấp thuận vị trí đấu nối tạm vào đường bộ đang khai thác", type: "toan-trinh", group: "giao-thong-van-tai" },
  { stt: 7, code: "1.000419.01", title: "Thủ tục đăng ký khai tử lưu động", type: "toan-trinh", group: "ho-tich-tu-phap" },
  { stt: 8, code: "1.000593.01", title: "Thủ tục đăng ký kết hôn lưu động", type: "toan-trinh", group: "ho-tich-tu-phap" },
  { stt: 9, code: "1.000656.02", title: "Thủ tục đăng ký khai tử", type: "toan-trinh", group: "ho-tich-tu-phap" },
  { stt: 10, code: "1.000689.01", title: "Thủ tục đăng ký khai sinh kết hợp đăng ký nhận cha, mẹ, con", type: "toan-trinh", group: "ho-tich-tu-phap" },
  { stt: 11, code: "1.000691.01", title: "Công nhận trường trung học đạt chuẩn Quốc gia", type: "mot-phan", group: "giao-duc-dao-tao" },
  { stt: 12, code: "1.000711.01", title: "Cấp Chứng nhận trường trung học đạt kiểm định chất lượng giáo dục", type: "mot-phan", group: "giao-duc-dao-tao" },
  { stt: 13, code: "1.000713.01", title: "Cấp Chứng nhận trường tiểu học đạt kiểm định chất lượng giáo dục", type: "mot-phan", group: "giao-duc-dao-tao" },
  { stt: 14, code: "1.000893.01", title: "Thủ tục đăng ký khai sinh có yếu tố nước ngoài cho người đã có hồ sơ, giấy tờ cá nhân", type: "toan-trinh", group: "ho-tich-tu-phap" },
  { stt: 15, code: "1.000894.02", title: "Thủ tục đăng ký kết hôn", type: "toan-trinh", group: "ho-tich-tu-phap" },
  { stt: 16, code: "1.001022.01", title: "Thủ tục đăng ký nhận cha, mẹ, con", type: "toan-trinh", group: "ho-tich-tu-phap" },
  { stt: 17, code: "1.001193.02", title: "Thủ tục đăng ký khai sinh", type: "toan-trinh", group: "ho-tich-tu-phap" },
  { stt: 18, code: "1.001257.01", title: "Giải quyết trợ cấp một lần đối với người có thành tích tham gia kháng chiến đã được tặng Bằng khen của Thủ tướng Chính phủ, Bằng khen của Chủ tịch Hội đồng Bộ trưởng hoặc Bằng khen của Bộ trưởng, Thủ trưởng cơ quan ngang bộ, Thủ trưởng cơ quan thuộc Chính phủ, Bằng khen của Chủ tịch Ủy ban nhân dân …", type: "mot-phan", group: "nguoi-co-cong" },
  { stt: 19, code: "1.001266.01", title: "Chấm dứt hoạt động hộ kinh doanh", type: "toan-trinh", group: "kinh-te-doanh-nghiep" },
  { stt: 20, code: "1.001570.01", title: "Tạm ngừng kinh doanh, tiếp tục kinh doanh trước thời hạn đã thông báo của hộ kinh doanh", type: "toan-trinh", group: "kinh-te-doanh-nghiep" },
  { stt: 21, code: "1.001612.01", title: "Đăng ký thành lập hộ kinh doanh", type: "toan-trinh", group: "kinh-te-doanh-nghiep" },
  { stt: 22, code: "1.001622.01", title: "Hỗ trợ ăn trưa đối với trẻ em mẫu giáo", type: "mot-phan", group: "giao-duc-dao-tao" },
  { stt: 23, code: "1.001639.01", title: "Giải thể trường tiểu học (theo đề nghị của tổ chức, cá nhân đề nghị thành lập trường tiểu học)", type: "mot-phan", group: "giao-duc-dao-tao" },
  { stt: 24, code: "1.001653.01", title: "Đổi, cấp lại Giấy xác nhận khuyết tật", type: "mot-phan", group: "bao-tro-xa-hoi" },
  { stt: 25, code: "1.001662.01", title: "Đăng ký khai thác nước dưới đất", type: "toan-trinh", group: "thuy-loi-moi-truong" },
  { stt: 26, code: "1.001669.01", title: "Thủ tục đăng ký giám hộ có yếu tố nước ngoài", type: "toan-trinh", group: "ho-tich-tu-phap" },
  { stt: 27, code: "1.001686.01", title: "Cấp Giấy chứng nhận đủ điều kiện buôn bán thuốc thú y", type: "toan-trinh", group: "nong-nghiep-thuy-san" },
  { stt: 28, code: "1.001695.01", title: "Thủ tục đăng ký khai sinh kết hợp đăng ký nhận cha, mẹ, con có yếu tố nước ngoài", type: "toan-trinh", group: "ho-tich-tu-phap" },
  { stt: 29, code: "1.001699.01", title: "Xác định, xác định lại mức độ khuyết tật và cấp Giấy xác nhận khuyết tật", type: "mot-phan", group: "bao-tro-xa-hoi" },
  { stt: 30, code: "1.001714.01", title: "Cấp học bổng và hỗ trợ kinh phí mua phương tiện, đồ dùng học tập dùng riêng cho người khuyết tật học tại các cơ sở giáo dục", type: "mot-phan", group: "giao-duc-dao-tao" },
  { stt: 31, code: "1.001731.01", title: "Hỗ trợ chi phí mai táng cho đối tượng bảo trợ xã hội", type: "mot-phan", group: "bao-tro-xa-hoi" },
  { stt: 32, code: "1.001766.01", title: "Thủ tục đăng ký khai tử có yếu tố nước ngoài", type: "toan-trinh", group: "ho-tich-tu-phap" },
  { stt: 33, code: "1.001776.01", title: "Thực hiện, điều chỉnh, thôi hưởng trợ cấp xã hội hàng tháng, hỗ trợ kinh phí chăm sóc, nuôi dưỡng hàng tháng", type: "mot-phan", group: "bao-tro-xa-hoi" },
  { stt: 34, code: "1.002211.01", title: "Thủ tục công nhận hòa giải viên (cấp xã)", type: "toan-trinh", group: "ho-tich-tu-phap" },
  { stt: 35, code: "1.002372.01", title: "Xác nhận việc trình kháng nghị hàng hải", type: "toan-trinh", group: "giao-thong-van-tai" },
  { stt: 36, code: "1.002693.01", title: "Cấp giấy phép chặt hạ, dịch chuyển cây xanh", type: "toan-trinh", group: "dat-dai-lam-nghiep" },
  { stt: 37, code: "1.003347.01", title: "Phê duyệt, công bố công khai quy trình vận hành hồ chứa thủy lợi thuộc thẩm quyền của Chủ tịch UBND cấp xã", type: "toan-trinh", group: "thuy-loi-moi-truong" },
  { stt: 38, code: "1.003434.01", title: "Hỗ trợ dự án liên kết (cấp xã)", type: "toan-trinh", group: "nong-nghiep-thuy-san" },
  { stt: 39, code: "1.003440.01", title: "Thẩm định, phê duyệt phương án ứng phó với tình huống khẩn cấp thuộc thẩm quyền của UBND cấp xã", type: "toan-trinh", group: "thuy-loi-moi-truong" },
  { stt: 40, code: "1.003446.01", title: "Thẩm định, phê duyệt phương án ứng phó thiên tai cho công trình, vùng hạ du đập trong quá trình thi công thuộc thẩm quyền của UBND cấp xã", type: "toan-trinh", group: "thuy-loi-moi-truong" },
  { stt: 41, code: "1.003471.01", title: "Phê duyệt đề cương, kết quả kiểm định an toàn đập, hồ chứa thủy lợi thuộc thẩm quyền của Chủ tịch UBND cấp xã", type: "toan-trinh", group: "thuy-loi-moi-truong" },
  { stt: 42, code: "1.003583.01", title: "Thủ tục đăng ký khai sinh lưu động", type: "toan-trinh", group: "ho-tich-tu-phap" },
  { stt: 43, code: "1.003586.01", title: "Cấp giấy chứng nhận đăng ký tạm thời tàu cá, tàu phục vụ nuôi trồng thủy sản", type: "toan-trinh", group: "nong-nghiep-thuy-san" },
  { stt: 44, code: "1.003596.01", title: "Phê duyệt kế hoạch khuyến nông địa phương (cấp xã)", type: "mot-phan", group: "nong-nghiep-thuy-san" },
  { stt: 45, code: "1.003622.01", title: "Thủ tục thông báo tổ chức lễ hội cấp xã", type: "toan-trinh", group: "van-hoa-ton-giao" },
  { stt: 46, code: "1.003634.01", title: "Cấp lại giấy chứng nhận đăng ký tàu cá, tàu phục vụ nuôi trồng thủy sản", type: "toan-trinh", group: "nong-nghiep-thuy-san" },
  { stt: 47, code: "1.003650.01", title: "Cấp giấy chứng nhận đăng ký tàu cá, tàu phục vụ nuôi trồng thủy sản", type: "toan-trinh", group: "nong-nghiep-thuy-san" },
  { stt: 48, code: "1.003658.01", title: "Công bố lại hoạt động bến thủy nội địa", type: "toan-trinh", group: "giao-thong-van-tai" },
  { stt: 49, code: "1.003681.01", title: "Xóa đăng ký tàu cá, tàu phục vụ nuôi trồng thủy sản", type: "toan-trinh", group: "nong-nghiep-thuy-san" },
  { stt: 50, code: "1.003702.01", title: "Hỗ trợ học tập đối với trẻ mẫu giáo, học sinh tiểu học, học sinh trung học cơ sở, sinh viên các dân tộc thiểu số rất ít người", type: "mot-phan", group: "giao-duc-dao-tao" },
  { stt: 51, code: "1.003930.01", title: "Cấp lại Giấy chứng nhận đăng ký phương tiện", type: "toan-trinh", group: "giao-thong-van-tai" },
  { stt: 52, code: "1.003956.01", title: "Công nhận và giao quyền quản lý cho tổ chức cộng đồng (thuộc địa bàn quản lý)", type: "toan-trinh", group: "nong-nghiep-thuy-san" },
  { stt: 53, code: "1.003970.01", title: "Đăng ký lại phương tiện trong trường hợp chuyển quyền sở hữu phương tiện đồng thời thay đổi cơ quan đăng ký phương tiện", type: "toan-trinh", group: "giao-thong-van-tai" },
  { stt: 54, code: "1.004002.01", title: "Đăng ký lại phương tiện trong trường hợp chuyển quyền sở hữu phương tiện nhưng không thay đổi cơ quan đăng ký phương tiện", type: "toan-trinh", group: "giao-thong-van-tai" },
  { stt: 55, code: "1.004036.01", title: "Đăng ký lại phương tiện trong trường hợp chuyển từ cơ quan đăng ký khác sang cơ quan đăng ký phương tiện thủy nội địa", type: "toan-trinh", group: "giao-thong-van-tai" },
  { stt: 56, code: "1.004047.01", title: "Đăng ký phương tiện lần đầu đối với phương tiện đang khai thác trên đường thủy nội địa", type: "toan-trinh", group: "giao-thong-van-tai" },
  { stt: 57, code: "1.004088.01", title: "Đăng ký phương tiện lần đầu đối với phương tiện chưa khai thác trên đường thủy nội địa", type: "toan-trinh", group: "giao-thong-van-tai" },
  { stt: 58, code: "1.004179.01", title: "Cấp giấy phép khai thác nước mặt, nước biển (đối với các trường hợp quy định tại khoản 2 Điều 15 Nghị định số 54/2024/NĐ-CP, được sửa đổi, bổ sung bởi khoản 12 Điều 2 Nghị định số 23/2026/NĐ-CP)", type: "toan-trinh", group: "thuy-loi-moi-truong" },
  { stt: 59, code: "1.004211.01", title: "Gia hạn, điều chỉnh giấy phép khai thác nước dưới đất đối với công trình có quy mô dưới 5.000 m3/ngày đêm", type: "toan-trinh", group: "thuy-loi-moi-truong" },
  { stt: 60, code: "1.004223.01", title: "Cấp giấy phép khai thác nước dưới đất đối với công trình có quy mô dưới 5.000 m3/ngày đêm", type: "toan-trinh", group: "thuy-loi-moi-truong" },
  { stt: 61, code: "1.004228.01", title: "Gia hạn, điều chỉnh giấy phép thăm dò nước dưới đất đối với công trình có quy mô dưới 5.000 m3/ngày đêm", type: "toan-trinh", group: "thuy-loi-moi-truong" },
  { stt: 62, code: "1.004232.01", title: "Cấp giấy phép thăm dò nước dưới đất đối với công trình có quy mô dưới 5.000 m3/ngày đêm", type: "toan-trinh", group: "thuy-loi-moi-truong" },
  { stt: 63, code: "1.004283.01", title: "Điều chỉnh tiền cấp quyền khai thác tài nguyên nước", type: "toan-trinh", group: "thuy-loi-moi-truong" },
  { stt: 64, code: "1.004359.01", title: "Cấp, cấp lại Giấy phép khai thác thủy sản", type: "toan-trinh", group: "nong-nghiep-thuy-san" },
  { stt: 65, code: "1.004478.01", title: "Công bố mở cảng cá loại III", type: "toan-trinh", group: "nong-nghiep-thuy-san" },
  { stt: 66, code: "1.004498.01", title: "Sửa đổi, bổ sung nội dung quyết định công nhận và giao quyền quản lý cho tổ chức cộng đồng (thuộc địa bàn quản lý)", type: "mot-phan", group: "nong-nghiep-thuy-san" },
  { stt: 67, code: "1.004563.01", title: "Sáp nhập, chia, tách trường tiểu học", type: "mot-phan", group: "giao-duc-dao-tao" },
  { stt: 68, code: "1.004656.01", title: "Xác nhận nguồn gốc loài thủy sản thuộc Phụ lục Công ước quốc tế về buôn bán các loài động vật, thực vật hoang dã nguy cấp; loài thủy sản nguy cấp, quý, hiếm có nguồn gốc khai thác từ tự nhiên", type: "toan-trinh", group: "nong-nghiep-thuy-san" },
  { stt: 69, code: "1.004680.01", title: "Xác nhận nguồn gốc loài thủy sản thuộc Phụ lục Công ước quốc tế về buôn bán các loài động vật, thực vật hoang dã nguy cấp và các loài thủy sản nguy cấp, quý, hiếm có nguồn gốc từ nuôi trồng", type: "toan-trinh", group: "nong-nghiep-thuy-san" },
  { stt: 70, code: "1.004746.01", title: "Thủ tục đăng ký lại kết hôn", type: "toan-trinh", group: "ho-tich-tu-phap" },
  { stt: 71, code: "1.004772.01", title: "Thủ tục đăng ký khai sinh cho người đã có hồ sơ, giấy tờ cá nhân", type: "toan-trinh", group: "ho-tich-tu-phap" },
  { stt: 72, code: "1.004827.01", title: "Thủ tục đăng ký khai tử có yếu tố nước ngoài tại khu vực biên giới", type: "toan-trinh", group: "ho-tich-tu-phap" },
  { stt: 73, code: "1.004837.01", title: "Thủ tục đăng ký giám hộ", type: "toan-trinh", group: "ho-tich-tu-phap" },
  { stt: 74, code: "1.004839.01", title: "Cấp lại Giấy chứng nhận đủ điều kiện buôn bán thuốc thú y", type: "toan-trinh", group: "nong-nghiep-thuy-san" },
  { stt: 75, code: "1.004844.01", title: "Cấp lại Giấy chứng nhận đăng ký phương tiện giao thông đường sắt", type: "toan-trinh", group: "giao-thong-van-tai" },
  { stt: 76, code: "1.004845.01", title: "Thủ tục đăng ký chấm dứt giám hộ", type: "toan-trinh", group: "ho-tich-tu-phap" },
  { stt: 77, code: "1.004859.01", title: "Thủ tục thay đổi, cải chính, bổ sung thông tin hộ tịch, xác định lại dân tộc", type: "toan-trinh", group: "ho-tich-tu-phap" },
  { stt: 78, code: "1.004873.01", title: "Thủ tục cấp Giấy xác nhận tình trạng hôn nhân", type: "toan-trinh", group: "ho-tich-tu-phap" },
  { stt: 79, code: "1.004884.01", title: "Thủ tục đăng ký lại khai sinh", type: "toan-trinh", group: "ho-tich-tu-phap" },
  { stt: 80, code: "1.004901.01", title: "Cấp đổi Giấy chứng nhận đăng ký hợp tác xã, liên hiệp hợp tác xã", type: "toan-trinh", group: "kinh-te-doanh-nghiep" },
  { stt: 81, code: "1.004941.01", title: "Đăng ký nhận chăm sóc thay thế cho trẻ em đối với cá nhân, người đại diện gia đình nhận chăm sóc thay thế không phải là người thân thích của trẻ em", type: "mot-phan", group: "bao-tro-xa-hoi" },
  { stt: 82, code: "1.004944.01", title: "Chấm dứt việc chăm sóc thay thế cho trẻ em", type: "mot-phan", group: "bao-tro-xa-hoi" },
  { stt: 83, code: "1.004946.01", title: "Áp dụng các biện pháp can thiệp khẩn cấp hoặc tạm thời cách ly trẻ em khỏi môi trường hoặc người gây tổn hại cho trẻ em", type: "mot-phan", group: "bao-tro-xa-hoi" },
  { stt: 84, code: "1.004964.01", title: "Giải quyết chế độ trợ cấp một lần đối với người được cử làm chuyên gia sang giúp Lào, Căm-pu-chi-a", type: "toan-trinh", group: "nguoi-co-cong" },
  { stt: 85, code: "1.004979.01", title: "Thông báo thay đổi nội dung đăng ký hợp tác xã, liên hiệp hợp tác xã; Thông báo thay đổi nội dung đăng ký đối với hợp tác xã, liên hiệp hợp tác xã bị tách, nhận sáp nhập", type: "toan-trinh", group: "kinh-te-doanh-nghiep" },
  { stt: 86, code: "1.004982.01", title: "Đăng ký giải thể hợp tác xã, liên hiệp hợp tác xã", type: "toan-trinh", group: "kinh-te-doanh-nghiep" },
  { stt: 87, code: "1.005010.01", title: "Chấm dứt hoạt động chi nhánh, văn phòng đại diện, địa điểm kinh doanh của hợp tác xã, liên hiệp hợp tác xã", type: "toan-trinh", group: "kinh-te-doanh-nghiep" },
  { stt: 88, code: "1.005040.01", title: "Xác nhận trình báo đường thủy nội địa hoặc trình báo đường thủy nội địa bổ sung", type: "toan-trinh", group: "giao-thong-van-tai" },
  { stt: 89, code: "1.005090.01", title: "Xét tuyển sinh vào trường phổ thông dân tộc nội trú", type: "mot-phan", group: "giao-duc-dao-tao" },
  { stt: 90, code: "1.005277.01", title: "Đăng ký thay đổi nội dung đăng ký hợp tác xã, liên hiệp hợp tác xã; Đăng ký thay đổi nội dung đối với trường hợp hợp tác xã, liên hiệp hợp tác xã bị tách, nhận sáp nhập", type: "toan-trinh", group: "kinh-te-doanh-nghiep" },
  { stt: 91, code: "1.005280.01", title: "Đăng ký thành lập hợp tác xã, liên hiệp hợp tác xã; đăng ký chuyển đổi tổ hợp tác thành hợp tác xã; đăng ký khi hợp tác xã, liên hiệp hợp tác xã chia, tách, hợp nhất", type: "toan-trinh", group: "kinh-te-doanh-nghiep" },
  { stt: 92, code: "1.005378.01", title: "Đăng ký thay đổi nội dung đăng ký hoạt động của chi nhánh, văn phòng đại diện, địa điểm kinh doanh của hợp tác xã, liên hiệp hợp tác xã", type: "toan-trinh", group: "kinh-te-doanh-nghiep" },
  { stt: 93, code: "1.005401.01", title: "Giao khu vực biển (cấp tỉnh)", type: "toan-trinh", group: "nong-nghiep-thuy-san" },
  { stt: 94, code: "1.005461.01", title: "Đăng ký lại khai tử - cấp tinh", type: "toan-trinh", group: "ho-tich-tu-phap" },
  { stt: 95, code: "1.006391.01", title: "Đăng ký lại phương tiện trong trường hợp chủ phương tiện thay đổi trụ sở hoặc nơi đăng ký hộ khẩu thường trú của chủ phương tiện sang đơn vị hành chính cấp tỉnh khác", type: "toan-trinh", group: "giao-thong-van-tai" },
  { stt: 96, code: "1.006468.01", title: "Thủ tục hải quan đối với hàng hoá kinh doanh tạm nhập-tái xuất", type: "toan-trinh", group: "linh-vuc-khac" },
  { stt: 97, code: "1.007919.01", title: "Thẩm định thiết kế, dự toán công trình lâm sinh hoặc thẩm định điều chỉnh thiết kế, dự toán công trình lâm sinh sử dụng vốn đầu tư công đối với công trình lâm sinh thuộc dự án do Chủ tịch Ủy ban nhân dân cấp xã quyết định đầu tư", type: "mot-phan", group: "dat-dai-lam-nghiep" },
  { stt: 98, code: "1.008004.01", title: "Chuyển đổi cơ cấu cây trồng, vật nuôi trên đất trồng lúa", type: "toan-trinh", group: "nong-nghiep-thuy-san" },
  { stt: 99, code: "1.008725.01", title: "Chuyển đổi trường tiểu học tư thục, trường trung học cơ sở tư thục và trường phổ thông tư thục có nhiều cấp học có cấp học cao nhất là trung học cơ sở do nhà đầu tư trong nước đầu tư sang trường phổ thông tư thục hoạt động không vì lợi nhuận", type: "mot-phan", group: "giao-duc-dao-tao" },
  { stt: 100, code: "1.008950.01", title: "Trợ cấp đối với trẻ em mầm non là con công nhân, người lao động làm việc tại khu công nghiệp", type: "mot-phan", group: "giao-duc-dao-tao" },
  { stt: 101, code: "1.008951.01", title: "Hỗ trợ đối với giáo viên mầm non làm việc tại cơ sở giáo dục mầm non dân lập, tư thục ở địa bàn có khu công nghiệp", type: "mot-phan", group: "giao-duc-dao-tao" },
  { stt: 102, code: "1.009407.01", title: "Công bố đáp ứng tiêu chuẩn chế biến, bào chế thuốc cổ truyền đối với cơ sở khám bệnh, chữa bệnh bằng y học cổ truyền trực thuộc quản lý của Sở Y tế", type: "mot-phan", group: "linh-vuc-khac" },
  { stt: 103, code: "1.009444.01", title: "Gia hạn hoạt động cảng, bến thủy nội địa", type: "toan-trinh", group: "giao-thong-van-tai" },
  { stt: 104, code: "1.009447.01", title: "Công bố đóng cảng, bến thủy nội địa", type: "toan-trinh", group: "giao-thong-van-tai" },
  { stt: 105, code: "1.009452.01", title: "Thỏa thuận thông số kỹ thuật xây dựng bến thủy nội địa", type: "toan-trinh", group: "giao-thong-van-tai" },
  { stt: 106, code: "1.009453.01", title: "Thỏa thuận thông số kỹ thuật xây dựng bến khách ngang sông, bến thủy nội địa phục vụ thi công công trình chính", type: "toan-trinh", group: "giao-thong-van-tai" },
  { stt: 107, code: "1.009454.01", title: "Công bố hoạt động bến thủy nội địa", type: "toan-trinh", group: "giao-thong-van-tai" },
  { stt: 108, code: "1.009455.01", title: "Công bố hoạt động bến khách ngang sông, bến thủy nội địa phục vụ thi công công trình chính", type: "toan-trinh", group: "giao-thong-van-tai" },
  { stt: 109, code: "1.009465.01", title: "Chấp thuận phương án bảo đảm an toàn giao thông", type: "toan-trinh", group: "giao-thong-van-tai" },
  { stt: 110, code: "1.009481.01", title: "Công nhận khu vực biển (cấp tỉnh)", type: "toan-trinh", group: "nong-nghiep-thuy-san" },
  { stt: 111, code: "1.009794.01", title: "Kiểm tra công tác nghiệm thu hoàn thành công trình của cơ quan chuyên môn về xây dựng tại địa phương", type: "toan-trinh", group: "xay-dung-quy-hoach" },
  { stt: 112, code: "1.010091.01", title: "Hỗ trợ khám chữa bệnh, trợ cấp tai nạn cho lực lượng xung kích phòng chống thiên tai cấp xã trong trường hợp chưa tham gia bảo hiểm y tế, bảo hiểm xã hội", type: "toan-trinh", group: "thuy-loi-moi-truong" },
  { stt: 113, code: "1.010092.01", title: "Trợ cấp tiền tuất, tai nạn (đối với trường hợp tai nạn suy giảm khả năng lao động từ 5% trở lên) cho lực lượng xung kích phòng chống thiên tai cấp xã chưa tham gia bảo hiểm xã hội", type: "toan-trinh", group: "thuy-loi-moi-truong" },
  { stt: 114, code: "1.010727.01", title: "Cấp giấy phép môi trường (cấp Tỉnh) ( 1.010727 )", type: "toan-trinh", group: "thuy-loi-moi-truong" },
  { stt: 115, code: "1.010729.01", title: "Cấp điều chỉnh giấy phép môi trường (cấp Tỉnh) (1.010729)", type: "toan-trinh", group: "thuy-loi-moi-truong" },
  { stt: 116, code: "1.010733.01", title: "Thẩm định báo cáo đánh giá tác động môi trường (Cấp tỉnh) (1.010733)", type: "toan-trinh", group: "thuy-loi-moi-truong" },
  { stt: 117, code: "1.010736.01", title: "Tham vấn trong đánh giá tác động môi trường (cấp xã) (1.010736)", type: "toan-trinh", group: "thuy-loi-moi-truong" },
  { stt: 118, code: "1.010772.01", title: "Cấp Bằng “Tổ quốc ghi công”", type: "toan-trinh", group: "nguoi-co-cong" },
  { stt: 119, code: "1.010774.01", title: "Cấp Bằng “Tổ quốc ghi công” đối với người hy sinh nhưng chưa được cấp Bằng “Tổ quốc ghi công” mà thân nhân đã được giải quyết chế độ ưu đãi từ ngày 31 tháng 12 năm 1994 trở về trước", type: "mot-phan", group: "nguoi-co-cong" },
  { stt: 120, code: "1.010775.01", title: "Cấp Bằng “Tổ quốc ghi công” đối với người hy sinh thuộc các trường hợp quy định tại Điều 14 Pháp lệnh nhưng chưa được cấp Bằng “Tổ quốc ghi công” mà thân nhân đã được giải quyết chế độ ưu đãi từ ngày 01 tháng 01 năm 1995 đến ngày 30 tháng 9 năm 2006", type: "mot-phan", group: "nguoi-co-cong" },
  { stt: 121, code: "1.010777.01", title: "Cấp đổi Bằng “Tổ quốc ghi công”", type: "mot-phan", group: "nguoi-co-cong" },
  { stt: 122, code: "1.010778.01", title: "Cấp lại Bằng “Tổ quốc ghi công”", type: "toan-trinh", group: "nguoi-co-cong" },
  { stt: 123, code: "1.010781.01", title: "Cấp Bằng “Tổ quốc ghi công” đối với người hy sinh hoặc mất tích trong chiến tranh", type: "toan-trinh", group: "nguoi-co-cong" },
  { stt: 124, code: "1.010783.01", title: "Tiếp nhận người có công vào cơ sở nuôi dưỡng, điều dưỡng người có công do Bộ Nội vụ quản lý", type: "mot-phan", group: "nguoi-co-cong" },
  { stt: 125, code: "1.010788.01", title: "Công nhận và giải quyết chế độ ưu đãi người hoạt động cách mạng", type: "mot-phan", group: "nguoi-co-cong" },
  { stt: 126, code: "1.010801.01", title: "Giải quyết chế độ trợ cấp ưu đãi đối với thân nhân liệt sĩ", type: "mot-phan", group: "nguoi-co-cong" },
  { stt: 127, code: "1.010802.02", title: "Giải quyết chế độ ưu đãi đối với vợ hoặc chồng liệt sĩ lấy chồng hoặc vợ khác", type: "mot-phan", group: "nguoi-co-cong" },
  { stt: 128, code: "1.010803.01", title: "Giải quyết chế độ trợ cấp thờ cúng liệt sĩ.", type: "toan-trinh", group: "nguoi-co-cong" },
  { stt: 129, code: "1.010804.01", title: "Giải quyết chế độ ưu đãi đối với trường hợp tặng hoặc truy tặng danh hiệu vinh dự nhà nước “Bà mẹ Việt Nam anh hùng\"", type: "toan-trinh", group: "nguoi-co-cong" },
  { stt: 130, code: "1.010805.01", title: "Giải quyết chế độ ưu đãi đối với Anh hùng lực lượng vũ trang nhân dân, Anh hùng lao động trong thời kỳ kháng chiến hiện không công tác trong quân đội, công an", type: "mot-phan", group: "nguoi-co-cong" },
  { stt: 131, code: "1.010810.01", title: "Công nhận đối với người bị thương trong chiến tranh không thuộc quân đội, công an", type: "mot-phan", group: "nguoi-co-cong" },
  { stt: 132, code: "1.010811.02", title: "Cấp tiền mua phương tiện trợ giúp, dụng cụ chỉnh hình, phương tiện, thiết bị phục hồi chức năng đối với trường hợp đang sống tại gia đình hoặc đang được nuôi dưỡng tập trung tại các cơ sở nuôi dưỡng, điều dưỡng do địa phương quản lý", type: "mot-phan", group: "nguoi-co-cong" },
  { stt: 133, code: "1.010812.01", title: "Tiếp nhận người có công vào cơ sở nuôi dưỡng, điều dưỡng người có công do tỉnh quản lý", type: "mot-phan", group: "nguoi-co-cong" },
  { stt: 134, code: "1.010814.01", title: "Cấp bổ sung hoặc cấp lại giấy chứng nhận người có công do ngành Lao động - Thương binh và Xã hội quản lý và giấy chứng nhận thân nhân liệt sĩ", type: "mot-phan", group: "nguoi-co-cong" },
  { stt: 135, code: "1.010815.01", title: "Công nhận và giải quyết chế độ ưu đãi người hoạt động cách mạng.", type: "mot-phan", group: "nguoi-co-cong" },
  { stt: 136, code: "1.010816.01", title: "Công nhận và giải quyết chế độ ưu đãi người hoạt động kháng chiến bị nhiễm chất độc hóa học", type: "mot-phan", group: "nguoi-co-cong" },
  { stt: 137, code: "1.010817.01", title: "Công nhận và giải quyết chế độ con đẻ của người hoạt động kháng chiến bị nhiễm chất độc hóa học", type: "toan-trinh", group: "nguoi-co-cong" },
  { stt: 138, code: "1.010818.01", title: "Công nhận và giải quyết chế độ người hoạt động cách mạng, kháng chiến, bảo vệ tổ quốc, làm nghĩa vụ quốc tế bị địch bắt tù, đày", type: "mot-phan", group: "nguoi-co-cong" },
  { stt: 139, code: "1.010819.01", title: "Giải quyết chế độ người hoạt động kháng chiến giải phóng dân tộc, bảo vệ tổ quốc và làm nghĩa vụ quốc tế", type: "mot-phan", group: "nguoi-co-cong" },
  { stt: 140, code: "1.010820.01", title: "Giải quyết chế độ người có công giúp đỡ cách mạng.", type: "mot-phan", group: "nguoi-co-cong" },
  { stt: 141, code: "1.010821.01", title: "Giải quyết chế độ hỗ trợ để theo học đến trình độ đại học tại các cơ sở giáo dục thuộc hệ thống giáo dục quốc dân", type: "mot-phan", group: "nguoi-co-cong" },
  { stt: 142, code: "1.010824.01", title: "Hưởng trợ cấp khi người có công đang hưởng trợ cấp ưu đãi từ trần", type: "mot-phan", group: "nguoi-co-cong" },
  { stt: 143, code: "1.010825.01", title: "Bổ sung tình hình thân nhân trong hồ sơ liệt sĩ.", type: "toan-trinh", group: "nguoi-co-cong" },
  { stt: 144, code: "1.010829.02", title: "Di chuyển hài cốt liệt sĩ đang an táng tại nghĩa trang liệt sĩ đi nơi khác theo nguyện vọng của đại diện thân nhân hoặc người hưởng trợ cấp thờ cúng liệt sĩ", type: "toan-trinh", group: "nguoi-co-cong" },
  { stt: 145, code: "1.010830.01", title: "Di chuyển hài cốt liệt sĩ đang an táng ngoài nghĩa trang liệt sĩ về an táng tại nghĩa trang liệt sĩ theo nguyện vọng của đại diện thân nhân hoặc người hưởng trợ cấp thờ cúng liệt sĩ", type: "toan-trinh", group: "nguoi-co-cong" },
  { stt: 146, code: "1.010833.01", title: "Cấp giấy xác nhận thân nhân của người có công", type: "toan-trinh", group: "nguoi-co-cong" },
  { stt: 147, code: "1.011471.01", title: "Phê duyệt Phương án khai thác gỗ, thực vật rừng ngoài gỗ loài thông thường thuộc thẩm quyền giải quyết của Ủy ban nhân dân cấp xã", type: "toan-trinh", group: "dat-dai-lam-nghiep" },
  { stt: 148, code: "1.011518.01", title: "Trả lại giấy phép thăm dò nước dưới đất, giấy phép khai thác tài nguyên nước .", type: "toan-trinh", group: "thuy-loi-moi-truong" },
  { stt: 149, code: "1.011606.01", title: "Công nhận hộ nghèo, hộ cận nghèo; hộ thoát nghèo, hộ thoát cận nghèo định kỳ hằng năm", type: "toan-trinh", group: "bao-tro-xa-hoi" },
  { stt: 150, code: "1.011607.01", title: "Công nhận hộ nghèo, hộ cận nghèo thường xuyên hằng năm", type: "mot-phan", group: "bao-tro-xa-hoi" },
  { stt: 151, code: "1.011608.01", title: "Công nhận hộ thoát nghèo, hộ thoát cận nghèo thường xuyên hằng năm", type: "mot-phan", group: "bao-tro-xa-hoi" },
  { stt: 152, code: "1.011609.01", title: "Công nhận hộ làm nông nghiệp, lâm nghiệp, ngư nghiệp và diêm nghiệp có mức sống trung bình", type: "mot-phan", group: "bao-tro-xa-hoi" },
  { stt: 153, code: "1.012084.01", title: "Thủ tục cấm tiếp xúc theo Quyết định của Chủ tịch Ủy ban nhân dân cấp xã theo đề nghị của cơ quan, tổ chức cá nhân", type: "toan-trinh", group: "ho-tich-tu-phap" },
  { stt: 154, code: "1.012085.02", title: "Hủy bỏ Quyết định cấm tiếp xúc theo đơn đề nghị", type: "toan-trinh", group: "ho-tich-tu-phap" },
  { stt: 155, code: "1.012222.01", title: "Công nhận người có uy tín", type: "toan-trinh", group: "linh-vuc-khac" },
  { stt: 156, code: "1.012223.01", title: "Đưa ra khỏi danh sách và thay thế, bổ sung người có uy tín", type: "toan-trinh", group: "linh-vuc-khac" },
  { stt: 157, code: "1.012299.01", title: "Thủ tục thi tuyển Viên Chức (Nghị định số 85/2023/NĐ-CP)", type: "mot-phan", group: "linh-vuc-khac" },
  { stt: 158, code: "1.012300.01", title: "Thủ tục xét tuyển Viên chức (85/2023/NĐ-CP)", type: "toan-trinh", group: "linh-vuc-khac" },
  { stt: 159, code: "1.012301.01", title: "Thủ tục tiếp nhận vào viên chức không giữ chức vụ quản lý", type: "mot-phan", group: "linh-vuc-khac" },
  { stt: 160, code: "1.012422.01", title: "Đề nghị xét tặng Danh hiệu “Thầy thuốc Nhân dân”, “Thầy thuốc Ưu tú”", type: "mot-phan", group: "nguoi-co-cong" },
  { stt: 161, code: "1.012427.01", title: "Thành lập/mở rộng cụm công nghiệp", type: "toan-trinh", group: "kinh-te-doanh-nghiep" },
  { stt: 162, code: "1.012531.01", title: "Hỗ trợ tín dụng đầu tư trồng rừng gỗ lớn đối với chủ rừng là hộ gia đình, cá nhân", type: "mot-phan", group: "dat-dai-lam-nghiep" },
  { stt: 163, code: "1.012568.01", title: "Giao tài sản kết cấu hạ tầng chợ do cấp xã quản lý", type: "toan-trinh", group: "kinh-te-doanh-nghiep" },
  { stt: 164, code: "1.012569.01", title: "Thu hồi tài sản kết cấu hạ tầng chợ", type: "toan-trinh", group: "kinh-te-doanh-nghiep" },
  { stt: 165, code: "1.012582.01", title: "THỦ TỤC ĐỀ NGHỊ THAY ĐỔI ĐỊA ĐIỂM SINH HOẠT TÔN GIÁO TẬP TRUNG ĐẾN ĐỊA BÀN XÃ KHÁC (CẤP XÃ)", type: "toan-trinh", group: "van-hoa-ton-giao" },
  { stt: 166, code: "1.012584.01", title: "THỦ TỤC ĐỀ NGHỊ THAY ĐỔI ĐỊA ĐIỂM SINH HOẠT TÔN GIÁO TẬP TRUNG TRONG ĐỊA BÀN MỘT XÃ (CẤP XÃ)", type: "toan-trinh", group: "van-hoa-ton-giao" },
  { stt: 167, code: "1.012585.01", title: "THỦ TỤC ĐĂNG KÝ THAY ĐỔI NGƯỜI ĐẠI DIỆN CỦA NHÓM SINH HOẠT TÔN GIÁO TẬP TRUNG (CẤP XÃ)", type: "toan-trinh", group: "van-hoa-ton-giao" },
  { stt: 168, code: "1.012590.01", title: "THỦ TỤC ĐĂNG KÝ SINH HOẠT TÔN GIÁO TẬP TRUNG (CẤP XÃ)", type: "toan-trinh", group: "van-hoa-ton-giao" },
  { stt: 169, code: "1.012591.01", title: "THỦ TỤC ĐĂNG KÝ BỔ SUNG HOẠT ĐỘNG TÍN NGƯỠNG (CẤP XÃ)", type: "toan-trinh", group: "van-hoa-ton-giao" },
  { stt: 170, code: "1.012592.02", title: "THỦ TỤC ĐĂNG KÝ HOẠT ĐỘNG TÍN NGƯỠNG (CẤP XÃ)", type: "toan-trinh", group: "van-hoa-ton-giao" },
  { stt: 171, code: "1.012694.01", title: "Chuyển mục đích sử dụng rừng sang mục đích khác đối với cá nhân", type: "mot-phan", group: "dat-dai-lam-nghiep" },
  { stt: 172, code: "1.012749.01", title: "Hỗ trợ chi phí khuyến khích sử dụng hình thức hỏa táng", type: "toan-trinh", group: "bao-tro-xa-hoi" },
  { stt: 173, code: "1.012753.01", title: "Đăng ký đất đai, tài sản gắn liền với đất, cấp Giấy chứng nhận quyền sử dụng đất, quyền sở hữu tài sản gắn liền với đất lần đầu đối với tổ chức đang sử dụng đất", type: "mot-phan", group: "dat-dai-lam-nghiep" },
  { stt: 174, code: "1.012756.01", title: "Đăng ký đất đai lần đầu đối với trường hợp được Nhà nước giao đất để quản lý.", type: "toan-trinh", group: "dat-dai-lam-nghiep" },
  { stt: 175, code: "1.012766.01", title: "Xóa đăng ký thuê, cho thuê lại quyền sử dụng đất trong dự án xây dựng kinh doanh kết cấu hạ tầng", type: "toan-trinh", group: "dat-dai-lam-nghiep" },
  { stt: 176, code: "1.012781.01", title: "Đăng ký, cấp Giấy chứng nhận đối với thửa đất có diện tích tăng thêm do thay đổi ranh giới so với Giấy chứng nhận đã cấp", type: "toan-trinh", group: "dat-dai-lam-nghiep" },
  { stt: 177, code: "1.012782.01", title: "Đăng ký, cấp Giấy chứng nhận đối với trường hợp cá nhân, hộ gia đình đã được cấp Giấy chứng nhận một phần diện tích vào loại đất ở trước ngày 01 tháng 7 năm 2004, phần diện tích còn lại của thửa đất chưa được cấp Giấy chứng nhận", type: "toan-trinh", group: "dat-dai-lam-nghiep" },
  { stt: 178, code: "1.012783.01", title: "Cấp đổi Giấy chứng nhận quyền sử dụng đất, quyền sở hữu tài sản gắn liền với đất", type: "toan-trinh", group: "dat-dai-lam-nghiep" },
  { stt: 179, code: "1.012784.01", title: "Tách thửa hoặc hợp thửa đất.", type: "toan-trinh", group: "dat-dai-lam-nghiep" },
  { stt: 180, code: "1.012785.01", title: "Đăng ký, cấp Giấy chứng nhận đối với trường hợp đã chuyển quyền sử dụng đất trước ngày 01 tháng 8 năm 2024 mà bên chuyển quyền đã được cấp Giấy chứng nhận nhưng chưa thực hiện thủ tục chuyển quyền theo quy định", type: "toan-trinh", group: "dat-dai-lam-nghiep" },
  { stt: 181, code: "1.012786.01", title: "Cấp lại Giấy chứng nhận do bị mất", type: "toan-trinh", group: "dat-dai-lam-nghiep" },
  { stt: 182, code: "1.012787.01", title: "Đăng ký, cấp Giấy chứng nhận quyền sử dụng đất, quyền sở hữu tài sản gắn liền với đất cho người nhận chuyển nhượng quyền sử dụng đất, quyền sở hữu nhà ở, công trình xây dựng trong dự án bất động sản", type: "toan-trinh", group: "dat-dai-lam-nghiep" },
  { stt: 183, code: "1.012791.01", title: "Thu hồi Giấy chứng nhận đã cấp không đúng quy định của pháp luật đất đai do người sử dụng đất, chủ sở hữu tài sản gắn liền với đất phát hiện và cấp lại Giấy chứng nhận sau khi thu hồi", type: "toan-trinh", group: "dat-dai-lam-nghiep" },
  { stt: 184, code: "1.012793.01", title: "Đăng ký biến động đối với trường hợp thành viên của hộ gia đình hoặc cá nhân đang sử dụng đất thành lập doanh nghiệp tư nhân và sử dụng đất vào hoạt động sản xuất kinh doanh của doanh nghiệp", type: "toan-trinh", group: "dat-dai-lam-nghiep" },
  { stt: 185, code: "1.012796.01", title: "Đính chính Giấy chứng nhận đã cấp lần đầu có sai sót", type: "mot-phan", group: "dat-dai-lam-nghiep" },
  { stt: 186, code: "1.012812.01", title: "Hòa giải tranh chấp đất đai", type: "mot-phan", group: "dat-dai-lam-nghiep" },
  { stt: 187, code: "1.012817.01", title: "Xác định lại diện tích đất ở của hộ gia đình, cá nhân đã được cấp Giấy chứng nhận trước ngày 01 tháng 7 năm 2004", type: "mot-phan", group: "dat-dai-lam-nghiep" },
  { stt: 188, code: "1.012818.01", title: "Thu hồi Giấy chứng nhận đã cấp lần đầu không đúng quy định của pháp luật đất đai do người sử dụng đất, chủ sở hữu tài sản gắn liền với đất phát hiện và cấp lại Giấy chứng nhận sau khi thu hồi", type: "mot-phan", group: "dat-dai-lam-nghiep" },
  { stt: 189, code: "1.012821.01", title: "Thẩm định, phê duyệt phương án sử dụng đất", type: "toan-trinh", group: "dat-dai-lam-nghiep" },
  { stt: 190, code: "1.012836.01", title: "Hỗ trợ chi phí về vật tư phối giống nhân tạo gia súc gồm tinh đông lạnh, Nitơ lỏng, găng tay và dụng cụ dẫn tinh để phối giống cho trâu, bò cái; chi phí về liều tinh để thực hiện phối giống cho lợn nái, công cho người làm dịch vụ phối giống nhân tạo gia súc (trâu, bò)", type: "toan-trinh", group: "nong-nghiep-thuy-san" },
  { stt: 191, code: "1.012837.01", title: "Phê duyệt hỗ trợ kinh phí đào tạo, tập huấn để chuyển đổi từ chăn nuôi sang các nghề khác; chi phí cho cá nhân được đào tạo về kỹ thuật phối giống nhân tạo gia súc (trâu, bò); chi phí mua bình chứa Nitơ lỏng bảo quản tinh cho người làm dịch vụ phối giống nhân tạo gia súc (trâu, bò) đối với các chính sách sử dụng vốn sự nghiệp nguồn ngân sách nhà nước", type: "toan-trinh", group: "nong-nghiep-thuy-san" },
  { stt: 192, code: "1.012888.01", title: "Công nhận Ban quản trị nhà chung cư", type: "toan-trinh", group: "xay-dung-quy-hoach" },
  { stt: 193, code: "1.012922.01", title: "Kiểm tra hiện trường rừng trồng bị thiệt hại", type: "mot-phan", group: "dat-dai-lam-nghiep" },
  { stt: 194, code: "1.012963.01", title: "Thành lập hoặc cho phép thành lập trường tiểu học", type: "mot-phan", group: "giao-duc-dao-tao" },
  { stt: 195, code: "1.012964.01", title: "Thành lập hoặc cho phép thành lập trường trung học cơ sở, trường phổ thông có nhiều cấp học có cấp học cao nhất là trung học cơ sở", type: "mot-phan", group: "giao-duc-dao-tao" },
  { stt: 196, code: "1.012965.01", title: "Cho phép trường trung học cơ sở, trường phổ thông có nhiều cấp học có cấp học cao nhất là trung học cơ sở hoạt động giáo dục", type: "mot-phan", group: "giao-duc-dao-tao" },
  { stt: 197, code: "1.012967.01", title: "Sáp nhập, chia, tách trường trung học cơ sở, trường phổ thông có nhiều cấp học có cấp học cao nhất là trung học cơ sở", type: "mot-phan", group: "giao-duc-dao-tao" },
  { stt: 198, code: "1.012968.01", title: "Giải thể trường trung học cơ sở, trường phổ thông có nhiều cấp học có cấp học cao nhất là trung học cơ sở (Theo đề nghị của tổ chức, cá nhân thành lập trường)", type: "mot-phan", group: "giao-duc-dao-tao" },
  { stt: 199, code: "1.012969.01", title: "Thành lập hoặc cho phép thành lập trung tâm học tập cộng đồng", type: "mot-phan", group: "giao-duc-dao-tao" },
  { stt: 200, code: "1.012971.01", title: "Thành lập hoặc cho phép thành lập cơ sở giáo dục mầm non độc lập", type: "mot-phan", group: "giao-duc-dao-tao" },
  { stt: 201, code: "1.012973.01", title: "Sáp nhập, chia, tách cơ sở giáo dục mầm non độc lập", type: "mot-phan", group: "giao-duc-dao-tao" },
  { stt: 202, code: "1.012974.01", title: "Giải thể cơ sở giáo dục mầm non độc lập (theo đề nghị của tổ chức, cá nhân thành lập trường)", type: "mot-phan", group: "giao-duc-dao-tao" },
  { stt: 203, code: "1.012975.01", title: "Cho phép cơ sở giáo dục khác thực hiện chương trình giáo dục phổ thông cấp tiểu học", type: "mot-phan", group: "giao-duc-dao-tao" },
  { stt: 204, code: "1.013040.01", title: "Thủ tục khai, nộp phí bảo vệ môi trường đối với khí thải", type: "toan-trinh", group: "thuy-loi-moi-truong" },
  { stt: 205, code: "1.013061.01", title: "Cấp giấy phép thi công công trình trên đường bộ đang khai thác", type: "toan-trinh", group: "giao-thong-van-tai" },
  { stt: 206, code: "1.013128.01", title: "Thủ tục thẩm định và phê duyệt kế hoạch ứng phó sự cố tràn dầu của các cửa hàng bán lẻ xăng dầu trên đất liền, trên sông, trên biển và các cơ sở, dự án trên địa bàn xã không thuộc đối tượng kinh doanh, vận chuyển xăng dầu có nguy cơ xảy ra sự cố tràn dầu mức độ nhỏ (dung tích chứa dưới 50 m3)", type: "toan-trinh", group: "thuy-loi-moi-truong" },
  { stt: 207, code: "1.013225.01", title: "Cấp giấy phép xây dựng mới đối với công trình cấp III, cấp IV (Công trình không theo tuyến/Theo tuyến trong đô thị/Tín ngưỡng, tôn giáo/Tượng đài, tranh hoành tráng/Theo giai đoạn cho công trình không theo tuyến/Theo giai đoạn cho công trình theo tuyến trong đô thị/Dự án) và nhà ở riêng lẻ", type: "toan-trinh", group: "xay-dung-quy-hoach" },
  { stt: 208, code: "1.013226.01", title: "Cấp điều chỉnh giấy phép xây dựng đối với công trình cấp III, cấp IV (công trình Không theo tuyến/Theo tuyến trong đô thị/Tín ngưỡng, tôn giáo/Tượng đài, tranh hoành tráng/Theo giai đoạn cho công trình không theo tuyến/Theo giai đoạn cho công trình theo tuyến trong đô thị/Dự án) và nhà ở riêng lẻ", type: "toan-trinh", group: "xay-dung-quy-hoach" },
  { stt: 209, code: "1.013227.01", title: "Gia hạn giấy phép xây dựng đối với công trình cấp III, cấp IV (công trình Không theo tuyến/Theo tuyến trong đô thị/Tín ngưỡng, tôn giáo/Tượng đài, tranh hoành tráng/Sửa chữa, cải tạo/Theo giai đoạn cho công trình không theo tuyến/Theo giai đoạn cho công trình theo tuyến trong đô thị/Dự án) và nhà ở riêng lẻ", type: "toan-trinh", group: "xay-dung-quy-hoach" },
  { stt: 210, code: "1.013228.01", title: "Cấp lại giấy phép xây dựng đối với công trình cấp III, cấp IV (công trình Không theo tuyến/Theo tuyến trong đô thị/Tín ngưỡng, tôn giáo/Tượng đài, tranh hoành tráng/Sửa chữa, cải tạo/Theo giai đoạn cho công trình không theo tuyến/Theo giai đoạn cho công trình theo tuyến trong đô thị/Dự án) và nhà ở riêng lẻ", type: "toan-trinh", group: "xay-dung-quy-hoach" },
  { stt: 211, code: "1.013229.01", title: "Cấp giấy phép xây dựng sửa chữa, cải tạo đối với công trình cấp III, cấp IV (công trình Không theo tuyến/Theo tuyến trong đô thị/Tín ngưỡng, tôn giáo/Tượng đài, tranh hoành tráng/Theo giai đoạn cho công trình không theo tuyến/Theo giai đoạn cho công trình theo tuyến trong đô thị/Dự án) và nhà ở riêng lẻ", type: "toan-trinh", group: "xay-dung-quy-hoach" },
  { stt: 212, code: "1.013232.01", title: "Cấp giấy phép di dời đối với công trình cấp III, cấp IV (Công trình không theo tuyến/Theo tuyến trong đô thị/Tín ngưỡng, tôn giáo/Tượng đài, tranh hoành tráng/Theo giai đoạn cho công trình không theo tuyến/Theo giai đoạn cho công trình theo tuyến trong đô thị/Dự án) và nhà ở riêng lẻ", type: "toan-trinh", group: "xay-dung-quy-hoach" },
  { stt: 213, code: "1.013239.01", title: "Thẩm định Báo cáo nghiên cứu khả thi đầu tư xây dựng/Báo cáo nghiên cứu khả thi đầu tư xây dựng điều chỉnh", type: "toan-trinh", group: "xay-dung-quy-hoach" },
  { stt: 214, code: "1.013274.01", title: "Cấp phép sử dụng tạm thời lòng đường, vỉa hè vào mục đích khác", type: "toan-trinh", group: "giao-thong-van-tai" },
  { stt: 215, code: "1.013314.02", title: "Xác nhận về điều kiện diện tích bình quân nhà ở để đăng ký thường trú vào chỗ ở do thuê, mượn, ở nhờ; nhà ở, đất ở không có tranh chấp quyền sở hữu nhà ở, quyền sử dụng đất ở, không thuộc địa điểm không được đăng ký thường trú mới", type: "toan-trinh", group: "xay-dung-quy-hoach" },
  { stt: 216, code: "1.013694.01", title: "Chấp thuận thiết kế nút giao đấu nối đường nhánh vào đường chính đang khai thác", type: "toan-trinh", group: "giao-thong-van-tai" },
  { stt: 217, code: "1.013695.01", title: "Cấp phép thi công nút giao đấu nối đường nhánh vào đường chính đang khai thác", type: "toan-trinh", group: "giao-thong-van-tai" },
  { stt: 218, code: "1.013702.01", title: "Công nhận ban vận động thành lập hội", type: "toan-trinh", group: "van-hoa-ton-giao" },
  { stt: 219, code: "1.013703.01", title: "Thành lập hội", type: "toan-trinh", group: "van-hoa-ton-giao" },
  { stt: 220, code: "1.013704.02", title: "Báo cáo tổ chức đại hội thành lập, đại hội nhiệm kỳ, đại hội bất thường của hội", type: "toan-trinh", group: "van-hoa-ton-giao" },
  { stt: 221, code: "1.013706.01", title: "Thông báo kết quả đại hội và phê duyệt đổi tên hội, phê duyệt điều lệ hội", type: "toan-trinh", group: "van-hoa-ton-giao" },
  { stt: 222, code: "1.013707.02", title: "Chia, tách; sáp nhập; hợp nhất hội", type: "toan-trinh", group: "van-hoa-ton-giao" },
  { stt: 223, code: "1.013708.01", title: "Hội tự giải thể", type: "toan-trinh", group: "van-hoa-ton-giao" },
  { stt: 224, code: "1.013709.01", title: "Cho phép hội hoạt động trở lại sau khi bị đình chỉ có thời hạn", type: "toan-trinh", group: "van-hoa-ton-giao" },
  { stt: 225, code: "1.013710.01", title: "Hỗ trợ chi phí y tế và thu nhập thực tế bị mất hoặc giảm sút cho người đang trực tiếp tham gia hoạt động chữ thập đỏ bị tai nạn dẫn đến thiệt hại về sức khỏe", type: "toan-trinh", group: "bao-tro-xa-hoi" },
  { stt: 226, code: "1.013734.01", title: "Đăng ký hợp đồng lao động trực tiếp giao kết .", type: "toan-trinh", group: "bao-tro-xa-hoi" },
  { stt: 227, code: "1.013744.01", title: "Giải quyết chế độ đối với quân nhân, cán bộ đi chiến trường B,C,K trong thời kỳ chống Mỹ cứu nước không có thân nhân phải trực tiếp nuôi dưỡng và quân nhân, cán bộ được đảng cử ở lại miền nam hoạt động sau hiệp định Giơnevơ năm 1954 đối với cán bộ dân, chính, đảng thuộc diện Trung ương quản lý", type: "mot-phan", group: "nguoi-co-cong" },
  { stt: 228, code: "1.013749.01", title: "Giải quyết chế độ đối với quân nhân, cán bộ đi chiến trường B,C,K trong thời kỳ chống mỹ cứu nước không có thân nhân phải trực tiếp nuôi dưỡng và quân nhân, cán bộ được đảng cử ở lại miền nam hoạt động sau hiệp định Giơnevơ năm 1954 đối với cán bộ dân, chính, đảng", type: "mot-phan", group: "nguoi-co-cong" },
  { stt: 229, code: "1.013750.01", title: "Thăm viếng mộ liệt sĩ.", type: "toan-trinh", group: "nguoi-co-cong" },
  { stt: 230, code: "1.013791.01", title: "Thủ tục tiếp nhận hồ sơ đăng ký lễ hội quy mô cấp xã", type: "toan-trinh", group: "van-hoa-ton-giao" },
  { stt: 231, code: "1.013792.01", title: "Thủ tục cấp giấy chứng nhận đủ điều kiện hoạt động điểm cung cấp dịch vụ trò chơi điện tử công cộng", type: "toan-trinh", group: "kinh-te-doanh-nghiep" },
  { stt: 232, code: "1.013793.01", title: "Thủ tục sửa đổi, bổ sung giấy chứng nhận đủ điều kiện hoạt động điểm cung cấp dịch vụ trò chơi điện tử công cộng", type: "toan-trinh", group: "kinh-te-doanh-nghiep" },
  { stt: 233, code: "1.013794.01", title: "Thủ tục gia hạn giấy chứng nhận đủ điều kiện hoạt động điểm cung cấp dịch vụ trò chơi điện tử công cộng", type: "toan-trinh", group: "kinh-te-doanh-nghiep" },
  { stt: 234, code: "1.013796.01", title: "THỦ TỤC ĐỀ NGHỊ TỔ CHỨC ĐẠI HỘI CỦA TỔ CHỨC TÔN GIÁO, TỔ CHỨC TÔN GIÁO TRỰC THUỘC, TỔ CHỨC ĐƯỢC CẤP CHỨNG NHẬN ĐĂNG KÝ HOẠT ĐỘNG TÔN GIÁO CÓ ĐỊA BÀN HOẠT ĐỘNG Ở MỘT XÃ", type: "toan-trinh", group: "van-hoa-ton-giao" },
  { stt: 235, code: "1.013797.01", title: "THỦ TỤC ĐỀ NGHỊ TỔ CHỨC CUỘC LỄ NGOÀI CƠ SỞ TÔN GIÁO, ĐỊA ĐIỂM HỢP PHÁP ĐÃ ĐĂNG KÝ CÓ QUY MÔ TỔ CHỨC Ở MỘT XÃ", type: "toan-trinh", group: "van-hoa-ton-giao" },
  { stt: 236, code: "1.013798.01", title: "THỦ TỤC ĐỀ NGHỊ GIẢNG ĐẠO NGOÀI ĐỊA BÀN PHỤ TRÁCH, CƠ SỞ TÔN GIÁO, ĐỊA ĐIỂM HỢP PHÁP ĐÃ ĐĂNG KÝ CÓ QUY MÔ TỔ CHỨC TRONG MỘT XÃ", type: "toan-trinh", group: "van-hoa-ton-giao" },
  { stt: 237, code: "1.013831.01", title: "Đăng ký biến động quyền sử dụng đất, quyền sở hữu tài sản gắn liền với đất trong các trường hợp chuyển đổi quyền sử dụng đất nông nghiệp mà không theo phương án dồn điền, đổi thửa; chuyển nhượng, thừa kế, tặng cho quyền sử dụng đất, quyền sở hữu tài sản gắn liền với đất, góp vốn bằng quyền sử dụng đất, quyền sở hữu tài sản gắn liền với đất; cho thuê, cho thuê lại quyền sử dụng đất trong dự án xây dựng kinh doanh kết cấu hạ tầng; bán hoặc tặng cho hoặc để thừa kế hoặc góp vốn bằng tài sản gắn liền với đất thuê của Nhà nước theo hình thức thuê đất trả tiền hàng năm", type: "toan-trinh", group: "dat-dai-lam-nghiep" },
  { stt: 238, code: "1.013833.01", title: "Đăng ký biến động đối với trường hợp đổi tên hoặc thay đổi thông tin về người sử dụng đất, chủ sở hữu tài sản gắn liền với đất hoặc thay đổi số hiệu hoặc địa chỉ của thửa đất; thay đổi hạn chế quyền sử dụng đất, quyền sở hữu tài sản gắn liền với đất hoặc có thay đổi quyền đối với thửa đất liền kề; giảm diện tích thửa đất do sạt lở tự nhiên", type: "toan-trinh", group: "dat-dai-lam-nghiep" },
  { stt: 239, code: "1.013855.01", title: "Cấp giấy chứng nhận cơ sở đủ điều kiện an toàn thực phẩm đối với cơ sở kinh doanh dịch vụ ăn uống, cơ sở sản xuất thực phẩm thuộc phạm vi quản lý của Bộ Y tế", type: "mot-phan", group: "linh-vuc-khac" },
  { stt: 240, code: "1.013947.01", title: "Xác nhận tiếp tục sử dụng đất nông nghiệp", type: "toan-trinh", group: "dat-dai-lam-nghiep" },
  { stt: 241, code: "1.013949.01", title: "Giao đất, cho thuê đất, chuyển mục đích sử dụng đất đối với trường hợp giao đất, cho thuê đất không đấu giá quyền sử dụng đất, không đấu thầu lựa chọn nhà đầu tư thực hiện dự án có sử dụng đất; trường hợp giao đất, cho thuê đất thông qua đấu thầu lựa chọn nhà đầu tư thực hiện dự án có sử dụng đất; giao đất và giao rừng; cho thuê đất và cho thuê rừng, gia hạn sử dụng đất khi hết thời hạn sử dụng đất", type: "mot-phan", group: "dat-dai-lam-nghiep" },
  { stt: 242, code: "1.013950.01", title: "Chuyển hình thức giao đất, cho thuê đất.", type: "mot-phan", group: "dat-dai-lam-nghiep" },
  { stt: 243, code: "1.013952.01", title: "Điều chỉnh quyết định giao đất, cho thuê đất, cho phép chuyển mục đích sử dụng đất do thay đổi căn cứ quyết định giao đất, cho thuê đất, cho phép chuyển mục đích sử dụng đất; điều chỉnh thời hạn sử dụng đất của dự án đầu tư.", type: "mot-phan", group: "dat-dai-lam-nghiep" },
  { stt: 244, code: "1.013953.01", title: "Điều chỉnh quyết định giao đất, cho thuê đất, cho phép chuyển mục đích sử dụng đất do sai sót về ranh giới, vị trí, diện tích, mục đích sử dụng giữa bản đồ quy hoạch, bản đồ địa chính, quyết định giao đất, cho thuê đất, cho phép chuyển mục đích sử dụng đất và số liệu bàn giao đất trên thực địa", type: "mot-phan", group: "dat-dai-lam-nghiep" },
  { stt: 245, code: "1.013962.01", title: "Giao đất ở có thu tiền sử dụng đất không thông qua đấu giá, không đấu thầu lựa chọn nhà đầu tư thực hiện dự án có sử dụng đất đối với cá nhân là cán bộ, công chức, viên chức, sĩ quan tại ngũ, quân nhân chuyên nghiệp, công chức quốc phòng, công nhân và viên chức quốc phòng, sĩ quan, hạ sĩ quan, công nhân công an, người làm công tác cơ yếu và người làm công tác khác trong tổ chức cơ yếu hưởng lương từ ngân sách nhà nước mà chưa được giao đất ở, nhà ở; giáo viên, nhân viên y tế đang công tác tại các xã biên giới, hải đảo thuộc vùng có điều kiện kinh tế xã hội khó khăn, vùng có điều kiện kinh tế - xã hội đặc biệt khó khăn nhưng chưa có đất ở, nhà ở tại nơi công tác hoặc chưa được hưởng chính sách hỗ trợ về nhà ở theo quy định của pháp luật về nhà ở; cá nhân thường trú tại xã mà không có đất ở và chưa được Nhà nước giao đất ở hoặc chưa được hưởng chính sách hỗ trợ về nhà ở theo quy định của pháp luật về nhà ở", type: "toan-trinh", group: "dat-dai-lam-nghiep" },
  { stt: 246, code: "1.013965.01", title: "Sử dụng đất kết hợp đa mục đích, gia hạn phương án sử dụng đất kết hợp đa mục đích.", type: "toan-trinh", group: "dat-dai-lam-nghiep" },
  { stt: 247, code: "1.013967.01", title: "Giải quyết tranh chấp đất đai thuộc thẩm quyền của Chủ tịch Ủy ban nhân dân cấp xã", type: "mot-phan", group: "dat-dai-lam-nghiep" },
  { stt: 248, code: "1.013977.01", title: "Đăng ký biến động thay đổi quyền sử dụng đất, quyền sở hữu tài sản gắn liền với đất do chia, tách, hợp nhất, sáp nhập tổ chức hoặc chuyển đổi mô hình tổ chức, chuyển đổi loại hình doanh nghiệp theo quy định của pháp luật về doanh nghiệp; điều chỉnh quy hoạch xây dựng chi tiết; cấp Giấy chứng nhận cho từng thửa đất theo quy hoạch xây dựng chi tiết cho chủ đầu tư dự án có nhu cầu", type: "toan-trinh", group: "dat-dai-lam-nghiep" },
  { stt: 249, code: "1.013978.01", title: "Đăng ký đất đai, tài sản gắn liền với đất, cấp Giấy chứng nhận quyền sử dụng đất, quyền sở hữu tài sản gắn liền với đất lần đầu đối với hộ gia đình, cá nhân, cộng đồng dân cư, người gốc Việt Nam định cư ở nước ngoài", type: "mot-phan", group: "dat-dai-lam-nghiep" },
  { stt: 250, code: "1.013979.01", title: "Tặng cho quyền sử dụng đất cho Nhà nước hoặc cộng đồng dân cư hoặc mở rộng đường giao thông đối với trường hợp thửa đất chưa được cấp Giấy chứng nhận", type: "mot-phan", group: "dat-dai-lam-nghiep" },
  { stt: 251, code: "1.013980.01", title: "Đăng ký biến động đối với trường hợp thay đổi quyền sử dụng đất, quyền sở hữu tài sản gắn liền với đất theo thỏa thuận của các thành viên hộ gia đình hoặc của vợ và chồng; quyền sử dụng đất xây dựng công trình trên mặt đất phục vụ cho việc vận hành, khai thác sử dụng công trình ngầm, quyền sở hữu công trình ngầm; bán tài sản, điều chuyển, chuyển nhượng quyền sử dụng đất là tài sản công theo quy định của pháp luật về quản lý, sử dụng tài sản công; nhận quyền sử dụng đất, quyền sở hữu tài sản gắn liền với đất theo kết quả giải quyết tranh chấp, khiếu nại, tố cáo về đất đai hoặc bản án, quyết định của Tòa án, quyết định thi hành án của cơ quan thi hành án đã được thi hành; quyết định hoặc phán quyết của Trọng tài thương mại Việt Nam về giải quyết tranh chấp giữa các bên phát sinh từ hoạt động thương mại liên quan đến đất đai; nhận quyền sử dụng đất, quyền sở hữu tài sản gắn liền với đất do xử lý tài sản thế chấp là quyền sử dụng đất, tài sản gắn liền với đất đã được đăng ký, bao gồm cả xử lý khoản nợ có nguồn gốc từ khoản nợ xấu của tổ chức tín dụng, chi nhánh ngân hàng nước ngoài", type: "toan-trinh", group: "dat-dai-lam-nghiep" },
  { stt: 252, code: "1.013988.01", title: "Xóa ghi nợ tiền sử dụng đất, lệ phí trước bạ trên Giấy chứng nhận đã cấp", type: "toan-trinh", group: "dat-dai-lam-nghiep" },
  { stt: 253, code: "1.013992.01", title: "Đăng ký biến động chuyển mục đích sử dụng đất không phải xin phép cơ quan nhà nước có thẩm quyền", type: "toan-trinh", group: "dat-dai-lam-nghiep" },
  { stt: 254, code: "1.013993.01", title: "Đăng ký, cấp Giấy chứng nhận đối với trường hợp hộ gia đình, cá nhân đang sử dụng đất không đúng mục đích đã được Nhà nước công nhận quyền sử dụng đất trước ngày 01 tháng 7 năm 2014", type: "toan-trinh", group: "dat-dai-lam-nghiep" },
  { stt: 255, code: "1.013994.01", title: "Đăng ký, cấp Giấy chứng nhận đối với trường hợp chuyển nhượng dự án đầu tư có sử dụng đất", type: "toan-trinh", group: "dat-dai-lam-nghiep" },
  { stt: 256, code: "1.013995.01", title: "Đăng ký tài sản gắn liền với thửa đất đã được cấp Giấy chứng nhận hoặc đăng ký thay đổi về tài sản gắn liền với đất so với nội dung đã đăng ký, gia hạn thời hạn sở hữu nhà ở của tổ chức nước ngoài, cá nhân nước ngoài theo quy định của pháp luật về nhà ở nội dung đã đăng ký", type: "toan-trinh", group: "dat-dai-lam-nghiep" },
  { stt: 257, code: "1.013997.01", title: "Hỗ trợ cơ sở sản xuất bị thiệt hại do dịch bệnh động vật (cơ sở sản xuất không thuộc lực lượng vũ trang nhân dân)", type: "toan-trinh", group: "nong-nghiep-thuy-san" },
  { stt: 258, code: "1.014027.01", title: "Thực hiện, điều chỉnh, thôi hưởng trợ cấp hưu trí xã hội", type: "mot-phan", group: "bao-tro-xa-hoi" },
  { stt: 259, code: "1.014028.01", title: "Hỗ trợ chi phí mai táng đối với đối tượng hưởng trợ cấp hưu trí xã hội", type: "mot-phan", group: "bao-tro-xa-hoi" },
  { stt: 260, code: "1.014034.01", title: "Đăng ký cập nhật, bổ sung thông tin trong hồ sơ đăng ký hộ kinh doanh, hiệu đính thông tin đăng ký hộ kinh doanh", type: "toan-trinh", group: "kinh-te-doanh-nghiep" },
  { stt: 261, code: "1.014035.01", title: "Dừng thực hiện thủ tục đăng ký hộ kinh doanh", type: "toan-trinh", group: "kinh-te-doanh-nghiep" },
  { stt: 262, code: "1.014111.01", title: "Thi tuyển công chức", type: "mot-phan", group: "linh-vuc-khac" },
  { stt: 263, code: "1.014113.01", title: "Xét tuyển công chức", type: "toan-trinh", group: "linh-vuc-khac" },
  { stt: 264, code: "1.014116.01", title: "Tiếp nhận vào công chức không giữ chức vụ lãnh đạo, quản lý", type: "mot-phan", group: "linh-vuc-khac" },
  { stt: 265, code: "1.014155.01", title: "Thẩm định nhiệm vụ quy hoạch, nhiệm vụ điều chỉnh quy hoạch đô thị và nông thôn do nhà đầu tư đã được lựa chọn để thực hiện dự án đầu tư tổ chức lập", type: "toan-trinh", group: "xay-dung-quy-hoach" },
  { stt: 266, code: "1.014156.01", title: "Phê duyệt nhiệm vụ quy hoạch, nhiệm vụ điều chỉnh quy hoạch đô thị và nông thôn do nhà đầu tư đã được lựa chọn để thực hiện dự án đầu tư tổ chức lập", type: "toan-trinh", group: "xay-dung-quy-hoach" },
  { stt: 267, code: "1.014157.01", title: "Phê duyệt điều chỉnh cục bộ quy hoạch chi tiết xây dựng điểm dân cư nông thôn", type: "toan-trinh", group: "xay-dung-quy-hoach" },
  { stt: 268, code: "1.014158.01", title: "Cung cấp thông tin quy hoạch xây dựng", type: "toan-trinh", group: "xay-dung-quy-hoach" },
  { stt: 269, code: "1.014160.01", title: "Đăng ký thành lập tổ hợp tác theo Luật Hợp tác xã 2023", type: "toan-trinh", group: "kinh-te-doanh-nghiep" },
  { stt: 270, code: "1.014162.01", title: "Thông báo thay đổi nội dung đăng ký tổ hợp tác trên địa bàn xã", type: "toan-trinh", group: "kinh-te-doanh-nghiep" },
  { stt: 271, code: "1.014165.01", title: "Chấm dứt hoạt động của tổ hợp tác theo quyết định của các thành viên", type: "toan-trinh", group: "kinh-te-doanh-nghiep" },
  { stt: 272, code: "1.014170.01", title: "Cấp lại Giấy chứng nhận đăng ký tổ hợp tác do bị mất hoặc hư hỏng", type: "toan-trinh", group: "kinh-te-doanh-nghiep" },
  { stt: 273, code: "1.014175.01", title: "Xác nhận đối tượng hộ gia đình, cá nhân trực tiếp sản xuất nông nghiệp", type: "toan-trinh", group: "nong-nghiep-thuy-san" },
  { stt: 274, code: "1.014180.01", title: "Xác nhận quy mô trang trại chăn nuôi, trồng trọt trên địa bàn xã", type: "toan-trinh", group: "nong-nghiep-thuy-san" },
  { stt: 275, code: "1.014185.01", title: "Hỗ trợ kinh phí xây dựng công trình cấp nước sạch hộ gia đình nông thôn", type: "toan-trinh", group: "thuy-loi-moi-truong" },
  { stt: 276, code: "1.014190.01", title: "Xác nhận đăng ký cam kết bảo vệ nguồn nước sinh hoạt khu dân cư", type: "toan-trinh", group: "thuy-loi-moi-truong" },
  { stt: 277, code: "1.014195.01", title: "Đăng ký phương tiện chăn nuôi, thu hoạch thủy sản nội địa quy mô nhỏ", type: "toan-trinh", group: "nong-nghiep-thuy-san" },
  { stt: 278, code: "1.014200.01", title: "Thẩm định phương án tận thu vật liệu xây dựng thông thường phục vụ công trình nông thôn mới", type: "mot-phan", group: "thuy-loi-moi-truong" },
  { stt: 279, code: "1.014205.01", title: "Công nhận tổ chức quản lý vận hành công trình thủy lợi nhỏ, thủy lợi nội đồng", type: "toan-trinh", group: "thuy-loi-moi-truong" },
  { stt: 280, code: "1.014210.01", title: "Xác nhận đăng ký hợp đồng gia công, tiêu thụ sản phẩm nông lâm nghiệp", type: "toan-trinh", group: "nong-nghiep-thuy-san" },
  { stt: 281, code: "1.014215.01", title: "Hỗ trợ chi phí tiêm vắc xin phòng chống dịch bệnh cho gia súc, gia cầm", type: "toan-trinh", group: "nong-nghiep-thuy-san" },
  { stt: 282, code: "1.014220.01", title: "Xác nhận diện tích đất nông nghiệp bị ngập úng, hạn hán phục vụ miễn giảm thủy lợi phí", type: "toan-trinh", group: "thuy-loi-moi-truong" },
  { stt: 283, code: "1.014225.01", title: "Đăng ký kiểm tra vệ sinh thú y đối với cơ sở giết mổ nhỏ lẻ hộ gia đình", type: "toan-trinh", group: "nong-nghiep-thuy-san" },
  { stt: 284, code: "1.014230.01", title: "Cấp chứng thư xác nhận xuất xứ gỗ rừng trồng của hộ gia đình, cá nhân", type: "toan-trinh", group: "dat-dai-lam-nghiep" },
  { stt: 285, code: "1.014235.01", title: "Thủ tục giao rừng gắn với giao đất cho hộ gia đình, cá nhân cư trú tại xã", type: "mot-phan", group: "dat-dai-lam-nghiep" },
  { stt: 286, code: "1.014240.01", title: "Xác nhận bảng kê lâm sản khai thác từ rừng trồng sản xuất của hộ gia đình", type: "toan-trinh", group: "dat-dai-lam-nghiep" },
  { stt: 287, code: "1.014245.01", title: "Hỗ trợ kinh phí khoán bảo vệ rừng theo Nghị định của Chính phủ", type: "toan-trinh", group: "dat-dai-lam-nghiep" },
  { stt: 288, code: "1.014250.01", title: "Đăng ký trồng mới rừng sản xuất, rừng phòng hộ của hộ gia đình", type: "toan-trinh", group: "dat-dai-lam-nghiep" },
  { stt: 289, code: "1.014255.01", title: "Cấp Giấy chứng nhận quyền sử dụng đất cho diện tích đất lâm nghiệp được giao", type: "mot-phan", group: "dat-dai-lam-nghiep" },
  { stt: 290, code: "1.014260.01", title: "Thẩm định hồ sơ chuyển mục đích sử dụng đất nông nghiệp sang đất ở của hộ gia đình", type: "mot-phan", group: "dat-dai-lam-nghiep" },
  { stt: 291, code: "1.014265.01", title: "Đăng ký thế chấp, giải chấp quyền sử dụng đất nông nghiệp tại Ngân hàng CSXH", type: "toan-trinh", group: "dat-dai-lam-nghiep" },
  { stt: 292, code: "1.014270.01", title: "Xác nhận trích đo địa chính thửa đất dân cư nông thôn", type: "toan-trinh", group: "dat-dai-lam-nghiep" },
  { stt: 293, code: "1.014275.01", title: "Giải quyết tranh chấp ranh giới thửa đất giữa các hộ gia đình liền kề", type: "mot-phan", group: "dat-dai-lam-nghiep" },
  { stt: 294, code: "1.014280.01", title: "Xác nhận đất không có tranh chấp phục vụ thủ tục cấp GCNQSDĐ lần đầu", type: "toan-trinh", group: "dat-dai-lam-nghiep" },
  { stt: 295, code: "1.014285.01", title: "Cấp xác nhận nguồn gốc đất đai khai phá trước ngày 01/07/2004", type: "mot-phan", group: "dat-dai-lam-nghiep" },
  { stt: 296, code: "1.014290.01", title: "Thủ tục điều chỉnh mốc giới hành chính bãi sạt lở sông suối trên địa bàn xã", type: "toan-trinh", group: "dat-dai-lam-nghiep" },
  { stt: 297, code: "1.014295.01", title: "Cấp trích lục bản đồ địa chính thửa đất nông nghiệp cho công dân", type: "toan-trinh", group: "dat-dai-lam-nghiep" },
  { stt: 298, code: "1.014300.01", title: "Xác nhận hộ gia đình chưa được Nhà nước giao đất ở lần nào", type: "toan-trinh", group: "dat-dai-lam-nghiep" },
  { stt: 299, code: "1.014305.01", title: "Đăng ký gia hạn thời hạn sử dụng đất nông nghiệp hộ gia đình", type: "toan-trinh", group: "dat-dai-lam-nghiep" },
  { stt: 300, code: "1.014310.01", title: "Xác nhận hợp đồng thuê đất nông nghiệp giữa công dân với cơ quan nhà nước", type: "toan-trinh", group: "dat-dai-lam-nghiep" },
  { stt: 301, code: "1.014315.01", title: "Đăng ký biến động quyền sử dụng đất khi nhận thừa kế theo pháp luật", type: "toan-trinh", group: "dat-dai-lam-nghiep" },
  { stt: 302, code: "1.014320.01", title: "Xác nhận văn bản thỏa thuận phân chia di sản thừa kế đất đai", type: "toan-trinh", group: "ho-tich-tu-phap" },
  { stt: 303, code: "1.014325.01", title: "Chứng thực hợp đồng tặng cho quyền sử dụng đất và tài sản gắn liền với đất", type: "toan-trinh", group: "ho-tich-tu-phap" },
  { stt: 304, code: "1.014330.01", title: "Chứng thực văn bản từ bỏ quyền nhận di sản thừa kế đất đai", type: "toan-trinh", group: "ho-tich-tu-phap" },
  { stt: 305, code: "1.014335.01", title: "Chứng thực hợp đồng thế chấp tài sản gắn liền với đất nông nghiệp", type: "toan-trinh", group: "ho-tich-tu-phap" },
  { stt: 306, code: "1.014340.01", title: "Chứng thực di chúc cá nhân", type: "toan-trinh", group: "ho-tich-tu-phap" },
  { stt: 307, code: "1.014345.01", title: "Chứng thực sửa đổi, bổ sung, hủy bỏ di chúc đã chứng thực", type: "toan-trinh", group: "ho-tich-tu-phap" },
  { stt: 308, code: "1.014350.01", title: "Chứng thực bản sao từ bản chính giấy tờ, văn bản do cơ quan có thẩm quyền cấp", type: "toan-trinh", group: "ho-tich-tu-phap" },
  { stt: 309, code: "1.014355.01", title: "Chứng thực chữ ký cá nhân trong giấy tờ, văn bản cá nhân", type: "toan-trinh", group: "ho-tich-tu-phap" },
  { stt: 310, code: "1.014360.01", title: "Chứng thực chữ ký người dịch trong các văn bản giấy tờ tiếng dân tộc thiểu số", type: "toan-trinh", group: "ho-tich-tu-phap" },
  { stt: 311, code: "1.014365.01", title: "Cấp bản sao trích lục hộ tịch từ Sổ hộ tịch lưu trữ tại xã", type: "toan-trinh", group: "ho-tich-tu-phap" },
  { stt: 312, code: "1.014370.01", title: "Thủ tục đính chính thông tin sai sót trong Sổ hộ tịch cấp xã", type: "toan-trinh", group: "ho-tich-tu-phap" },
  { stt: 313, code: "1.014375.01", title: "Đăng ký nhận con nuôi trong nước", type: "toan-trinh", group: "ho-tich-tu-phap" },
  { stt: 314, code: "1.014380.01", title: "Đăng ký lại việc nuôi con nuôi trong nước", type: "toan-trinh", group: "ho-tich-tu-phap" },
  { stt: 315, code: "1.014385.01", title: "Thủ tục chấm dứt việc nuôi con nuôi theo quyết định của Tòa án", type: "toan-trinh", group: "ho-tich-tu-phap" },
  { stt: 316, code: "1.014390.01", title: "Cấp Giấy xác nhận tình trạng hôn nhân phục vụ mục đích vay vốn Ngân hàng CSXH", type: "toan-trinh", group: "ho-tich-tu-phap" },
  { stt: 317, code: "1.014395.01", title: "Thủ tục ghi chú việc ly hôn, hủy việc kết hôn đã giải quyết ở nước ngoài", type: "toan-trinh", group: "ho-tich-tu-phap" },
  { stt: 318, code: "1.014400.01", title: "Đăng ký khai sinh lưu động cho trẻ em vùng sâu, vùng xa xã Đăk Pxi", type: "toan-trinh", group: "ho-tich-tu-phap" },
  { stt: 319, code: "1.014405.01", title: "Đăng ký khai tử lưu động cho người cao tuổi, người neo đơn", type: "toan-trinh", group: "ho-tich-tu-phap" },
  { stt: 320, code: "1.014410.01", title: "Đăng ký kết hôn lưu động tại điểm thôn xa trung tâm xã", type: "toan-trinh", group: "ho-tich-tu-phap" },
  { stt: 321, code: "1.014415.01", title: "Xác nhận đối tượng học sinh, sinh viên thuộc hộ nghèo để miễn giảm học phí", type: "toan-trinh", group: "giao-duc-dao-tao" },
  { stt: 322, code: "1.014420.01", title: "Hỗ trợ chi phí học tập cho học sinh tiểu học, THCS vùng ĐKTKTĐKT", type: "toan-trinh", group: "giao-duc-dao-tao" },
  { stt: 323, code: "1.014425.01", title: "Cấp hỗ trợ tiền ăn trưa cho trẻ em mẫu giáo từ 3 đến 5 tuổi", type: "toan-trinh", group: "giao-duc-dao-tao" },
  { stt: 324, code: "1.014430.01", title: "Xác nhận đơn xin chuyển trường cho học sinh tiểu học, THCS trên địa bàn xã", type: "toan-trinh", group: "giao-duc-dao-tao" },
  { stt: 325, code: "1.014435.01", title: "Công nhận phổ cập giáo dục tiểu học và THCS mức độ 3 xã Đăk Pxi", type: "toan-trinh", group: "giao-duc-dao-tao" },
  { stt: 326, code: "1.014440.01", title: "Công nhận xã đạt chuẩn xóa nạn mù chữ mức độ 2", type: "toan-trinh", group: "giao-duc-dao-tao" },
  { stt: 327, code: "1.014445.01", title: "Hỗ trợ học bổng học sinh dân tộc thiểu số nghèo vượt khó", type: "toan-trinh", group: "giao-duc-dao-tao" },
  { stt: 328, code: "1.014450.01", title: "Cho phép thành lập lớp mầm non độc lập tư thục quy mô nhỏ", type: "mot-phan", group: "giao-duc-dao-tao" },
  { stt: 329, code: "1.014455.01", title: "Cấp phép hoạt động nhóm trẻ gia đình dưới 7 trẻ em", type: "toan-trinh", group: "giao-duc-dao-tao" },
  { stt: 330, code: "1.014460.01", title: "Kiểm tra điều kiện an toàn vệ sinh cơ sở mầm non độc lập", type: "toan-trinh", group: "giao-duc-dao-tao" },
  { stt: 331, code: "1.014465.01", title: "Xác nhận danh sách người có công với cách mạng được hỗ trợ nhà ở", type: "toan-trinh", group: "nguoi-co-cong" },
  { stt: 332, code: "1.014470.01", title: "Giải quyết chế độ điều dưỡng phục hồi sức khỏe tập trung cho thương binh", type: "toan-trinh", group: "nguoi-co-cong" },
  { stt: 333, code: "1.014475.01", title: "Cấp BHYT miễn phí cho thân nhân người có công với cách mạng", type: "toan-trinh", group: "nguoi-co-cong" },
  { stt: 334, code: "1.014480.01", title: "Giải quyết trợ cấp tuất hàng tháng cho thân nhân thương binh suy giảm 61% trở lên", type: "mot-phan", group: "nguoi-co-cong" },
  { stt: 335, code: "1.014485.01", title: "Hỗ trợ cải tạo, sửa chữa nhà ở cho hộ người có công bị hư hỏng", type: "toan-trinh", group: "nguoi-co-cong" },
  { stt: 336, code: "1.014490.01", title: "Chi trả phương tiện trợ giúp dụng cụ chỉnh hình cho người có công", type: "toan-trinh", group: "nguoi-co-cong" },
  { stt: 337, code: "1.014495.01", title: "Cấp lại Giấy chứng nhận thương binh, bệnh binh bị rách hỏng", type: "toan-trinh", group: "nguoi-co-cong" },
  { stt: 338, code: "1.014500.01", title: "Giải quyết trợ cấp một lần cho thân nhân bệnh binh từ trần", type: "toan-trinh", group: "nguoi-co-cong" },
  { stt: 339, code: "1.014505.01", title: "Lập hồ sơ đề nghị phong tặng danh hiệu Bà mẹ Việt Nam Anh hùng", type: "mot-phan", group: "nguoi-co-cong" },
  { stt: 340, code: "1.014510.01", title: "Xác nhận thông tin mộ liệt sĩ tại nghĩa trang liệt sĩ huyện", type: "toan-trinh", group: "nguoi-co-cong" },
  { stt: 341, code: "1.014515.01", title: "Cấp Giấy xác nhận hộ nghèo, hộ cận nghèo phục vụ thủ tục tín dụng", type: "toan-trinh", group: "bao-tro-xa-hoi" },
  { stt: 342, code: "1.014520.01", title: "Giải quyết trợ cấp đột xuất cho hộ gia đình bị hỏa hoạn, thiên tai", type: "toan-trinh", group: "bao-tro-xa-hoi" },
  { stt: 343, code: "1.014525.01", title: "Hỗ trợ gạo cứu đói giáp hạt cho các hộ nghèo tại các thôn khó khăn", type: "toan-trinh", group: "bao-tro-xa-hoi" },
  { stt: 344, code: "1.014530.01", title: "Cấp Giấy xác nhận khuyết tật nặng, đặc biệt nặng", type: "toan-trinh", group: "bao-tro-xa-hoi" },
  { stt: 345, code: "1.014535.01", title: "Giải quyết kinh phí chăm sóc người khuyết tật đặc biệt nặng tại gia đình", type: "toan-trinh", group: "bao-tro-xa-hoi" },
  { stt: 346, code: "1.014540.01", title: "Thủ tục nhận nuôi dưỡng trẻ em mồ côi cả cha lẫn mẹ", type: "toan-trinh", group: "bao-tro-xa-hoi" },
  { stt: 347, code: "1.014545.01", title: "Giải quyết trợ cấp cho người từ 80 tuổi trở lên không có lương hưu", type: "toan-trinh", group: "bao-tro-xa-hoi" },
  { stt: 348, code: "1.014550.01", title: "Cấp Thẻ Bảo hiểm y tế miễn phí cho đối tượng bảo trợ xã hội", type: "toan-trinh", group: "bao-tro-xa-hoi" },
  { stt: 349, code: "1.014555.01", title: "Xác nhận danh sách lao động làm việc không theo hợp đồng đề nghị hỗ trợ", type: "toan-trinh", group: "bao-tro-xa-hoi" },
  { stt: 350, code: "1.014560.01", title: "Đăng ký nhu cầu học nghề cho lao động nông thôn xã Đăk Pxi", type: "toan-trinh", group: "bao-tro-xa-hoi" },
  { stt: 351, code: "1.014565.01", title: "Cấp Giấy phép đào tạo lái xe mô tô hai bánh hạng A1 tại điểm lưu động", type: "toan-trinh", group: "giao-thong-van-tai" },
  { stt: 352, code: "1.014570.01", title: "Đăng ký xe máy chuyên dùng phục vụ sản xuất nông lâm nghiệp", type: "toan-trinh", group: "giao-thong-van-tai" },
  { stt: 353, code: "1.014575.01", title: "Nghiệm thu công trình giao thông nông thôn tuyến đường liên thôn", type: "toan-trinh", group: "giao-thong-van-tai" },
  { stt: 354, code: "1.014580.01", title: "Cấp phép thi công mặt đường bê tông nông thôn điểm đấu nối dân sinh", type: "toan-trinh", group: "giao-thong-van-tai" },
  { stt: 355, code: "1.014585.01", title: "Xác nhận hành lang an toàn giao thông đường bộ cấp xã quản lý", type: "toan-trinh", group: "giao-thong-van-tai" },
  { stt: 356, code: "1.014590.01", title: "Đăng ký quản lý xe thô sơ, xe tự chế phục vụ chở nông sản", type: "toan-trinh", group: "giao-thong-van-tai" },
  { stt: 357, code: "1.014595.01", title: "Cấp phép sử dụng tạm thời vỉa hè, lề đường tập kết vật liệu xây dựng", type: "toan-trinh", group: "giao-thong-van-tai" },
  { stt: 358, code: "1.014600.01", title: "Thông báo cắm mốc lộ giới đường xã, đường thôn", type: "toan-trinh", group: "giao-thong-van-tai" },
  { stt: 359, code: "1.014605.01", title: "Công nhận tuyến đường kiểu mẫu Nông thôn mới", type: "toan-trinh", group: "giao-thong-van-tai" },
  { stt: 360, code: "1.014610.01", title: "Xác nhận hiện trạng đường giao thông đi qua thửa đất đăng ký cấp Giấy chứng nhận", type: "toan-trinh", group: "giao-thong-van-tai" },
  { stt: 361, code: "1.014615.01", title: "Thẩm định phương án xử lý rác thải sinh hoạt khu dân cư tập trung", type: "toan-trinh", group: "thuy-loi-moi-truong" },
  { stt: 362, code: "1.014620.01", title: "Cấp xác nhận cam kết vệ sinh môi trường trại chăn nuôi quy mô hộ", type: "toan-trinh", group: "thuy-loi-moi-truong" },
  { stt: 363, code: "1.014625.01", title: "Kiểm tra xử lý ô nhiễm tiếng ồn, chất thải khu vực nông thôn", type: "toan-trinh", group: "thuy-loi-moi-truong" },
  { stt: 364, code: "1.014630.01", title: "Đăng ký tham gia Ngày Chủ nhật Xanh dọn dẹp cảnh quan môi trường", type: "toan-trinh", group: "thuy-loi-moi-truong" },
  { stt: 365, code: "1.014635.01", title: "Nghiệm thu hệ thống thoát nước mưa, nước thải khu dân cư nông thôn", type: "toan-trinh", group: "thuy-loi-moi-truong" },
  { stt: 366, code: "1.014640.01", title: "Cấp phép đào ao nạo vét lòng hồ chứa nước thủy lợi hộ gia đình", type: "toan-trinh", group: "thuy-loi-moi-truong" },
  { stt: 367, code: "1.014645.01", title: "Xác nhận khu vực nguồn nước không bị ô nhiễm hóa chất BVTV", type: "toan-trinh", group: "thuy-loi-moi-truong" },
  { stt: 368, code: "1.014650.01", title: "Cấp xác nhận hoàn thành công trình bảo vệ môi trường chăn nuôi", type: "toan-trinh", group: "thuy-loi-moi-truong" },
  { stt: 369, code: "1.014655.01", title: "Xác nhận danh sách hộ gia đình được cấp thùng phân loại rác tại nguồn", type: "toan-trinh", group: "thuy-loi-moi-truong" },
  { stt: 370, code: "1.014660.01", title: "Thủ tục đăng ký nộp phí bảo vệ môi trường đối với khai thác khoáng sản nhỏ", type: "toan-trinh", group: "thuy-loi-moi-truong" },
  { stt: 371, code: "1.014665.01", title: "Cấp phép kinh doanh vật tư nông nghiệp, giống cây trồng tại địa phương", type: "toan-trinh", group: "nong-nghiep-thuy-san" },
  { stt: 372, code: "1.014670.01", title: "Đăng ký tham gia mô hình trình diễn khuyến nông trồng cây ăn quả", type: "toan-trinh", group: "nong-nghiep-thuy-san" },
  { stt: 373, code: "1.014675.01", title: "Hỗ trợ mua giống lúa, giống ngô khôi phục sản xuất sau thiên tai", type: "toan-trinh", group: "nong-nghiep-thuy-san" },
  { stt: 374, code: "1.014680.01", title: "Xác nhận hộ gia đình tham gia chuỗi liên kết sản xuất tiêu thụ nông sản OCOP", type: "toan-trinh", group: "nong-nghiep-thuy-san" },
  { stt: 375, code: "1.014685.01", title: "Cấp Giấy chứng nhận mã số vùng trồng cây ăn quả nông hộ", type: "toan-trinh", group: "nong-nghiep-thuy-san" },
  { stt: 376, code: "1.014690.01", title: "Kiểm tra cấp chứng nhận cơ sở an toàn dịch bệnh chăn nuôi", type: "toan-trinh", group: "nong-nghiep-thuy-san" },
  { stt: 377, code: "1.014695.01", title: "Hỗ trợ xây dựng hầm Biogas xử lý chất thải chăn nuôi lợn", type: "toan-trinh", group: "nong-nghiep-thuy-san" },
  { stt: 378, code: "1.014700.01", title: "Cấp xác nhận sản phẩm đạt chuẩn OCOP 3 sao cấp huyện/xã", type: "toan-trinh", group: "nong-nghiep-thuy-san" },
  { stt: 379, code: "1.014705.01", title: "Hướng dẫn kỹ thuật phòng trừ sâu bệnh hại cây cà phê, cao su", type: "toan-trinh", group: "nong-nghiep-thuy-san" },
  { stt: 380, code: "1.014710.01", title: "Xác nhận danh sách hộ nuôi cá lồng bè trên sông, hồ thủy điện", type: "toan-trinh", group: "nong-nghiep-thuy-san" },
  { stt: 381, code: "1.014715.01", title: "Đăng ký thay đổi tên chủ hộ kinh doanh cá thể", type: "toan-trinh", group: "kinh-te-doanh-nghiep" },
  { stt: 382, code: "1.014720.01", title: "Đăng ký bổ sung ngành nghề kinh doanh nông sản, bách hóa", type: "toan-trinh", group: "kinh-te-doanh-nghiep" },
  { stt: 383, code: "1.014725.01", title: "Cấp Giấy chứng nhận đăng ký địa điểm kinh doanh của HKD", type: "toan-trinh", group: "kinh-te-doanh-nghiep" },
  { stt: 384, code: "1.014730.01", title: "Đăng ký tạm ngừng kinh doanh của hộ kinh doanh cá thể", type: "toan-trinh", group: "kinh-te-doanh-nghiep" },
  { stt: 385, code: "1.014735.01", title: "Xác nhận hộ kinh doanh chấp hành tốt chính sách thuế local", type: "toan-trinh", group: "kinh-te-doanh-nghiep" },
  { stt: 386, code: "1.014740.01", title: "Cấp Giấy phép bán lẻ thuốc lá, rượu tại điểm kinh doanh bách hóa", type: "toan-trinh", group: "kinh-te-doanh-nghiep" },
  { stt: 387, code: "1.014745.01", title: "Cấp lại Giấy phép kinh doanh bán lẻ do bị rách hoặc mất", type: "toan-trinh", group: "kinh-te-doanh-nghiep" },
  { stt: 388, code: "1.014750.01", title: "Đăng ký thuê điểm kinh doanh, gian hàng tại chợ nông thôn xã Đăk Pxi", type: "toan-trinh", group: "kinh-te-doanh-nghiep" },
  { stt: 389, code: "1.014755.01", title: "Xác nhận doanh thu hộ kinh doanh phục vụ kê khai thuế khoán", type: "toan-trinh", group: "kinh-te-doanh-nghiep" },
  { stt: 390, code: "1.014760.01", title: "Đăng ký tham gia hội chợ triển lãm sản phẩm đặc trưng của xã", type: "toan-trinh", group: "kinh-te-doanh-nghiep" },
  { stt: 391, code: "1.014765.01", title: "Đăng ký thành lập Câu lạc bộ Văn hóa Văn nghệ dân gian thôn", type: "toan-trinh", group: "van-hoa-ton-giao" },
  { stt: 392, code: "1.014770.01", title: "Đăng ký thành lập Đội thể dục thể thao quần chúng cấp xã", type: "toan-trinh", group: "van-hoa-ton-giao" },
  { stt: 393, code: "1.014775.01", title: "Cấp Giấy công nhận Danh hiệu Gia đình Văn hóa hàng năm", type: "toan-trinh", group: "van-hoa-ton-giao" },
  { stt: 394, code: "1.014780.01", title: "Cấp Giấy công nhận Thôn Văn hóa 3 năm liên tục", type: "toan-trinh", group: "van-hoa-ton-giao" },
  { stt: 395, code: "1.014785.01", title: "Thông báo biểu diễn nghệ thuật quần chúng quy mô cấp thôn/xã", type: "toan-trinh", group: "van-hoa-ton-giao" },
  { stt: 396, code: "1.014790.01", title: "Đăng ký tổ chức giải thi đấu thể thao phong trào xã Đăk Pxi", type: "toan-trinh", group: "van-hoa-ton-giao" },
  { stt: 397, code: "1.014795.01", title: "Thủ tục tiếp nhận thông báo xây dựng công trình phụ trợ cơ sở tôn giáo", type: "toan-trinh", group: "van-hoa-ton-giao" },
  { stt: 398, code: "1.014800.01", title: "Đăng ký người chủ trì lễ tôn giáo tại cơ sở tôn giáo hợp pháp", type: "toan-trinh", group: "van-hoa-ton-giao" },
  { stt: 399, code: "1.014805.01", title: "Xác nhận danh sách ban chức việc điểm sinh hoạt tôn giáo tập trung", type: "toan-trinh", group: "van-hoa-ton-giao" },
  { stt: 400, code: "1.014810.01", title: "Cấp phép treo băng rôn, khẩu hiệu tuyên truyền nhiệm vụ chính trị xã", type: "toan-trinh", group: "van-hoa-ton-giao" },
  { stt: 401, code: "1.014815.01", title: "Cấp phép xây dựng nhà ở riêng lẻ nông thôn quy mô dưới 3 tầng", type: "toan-trinh", group: "xay-dung-quy-hoach" },
  { stt: 402, code: "1.014820.01", title: "Cấp phép sửa đổi, cải tạo nhà ở nông thôn giáp mặt đường chính", type: "toan-trinh", group: "xay-dung-quy-hoach" },
  { stt: 403, code: "1.014825.01", title: "Gia hạn Giấy phép xây dựng nhà ở riêng lẻ nông thôn", type: "toan-trinh", group: "xay-dung-quy-hoach" },
  { stt: 404, code: "1.014830.01", title: "Cấp lại Giấy phép xây dựng nhà ở bị thất lạc hoặc hư hỏng", type: "toan-trinh", group: "xay-dung-quy-hoach" },
  { stt: 405, code: "1.014835.01", title: "Nghiệm thu hoàn thành đưa nhà ở riêng lẻ vào sử dụng", type: "toan-trinh", group: "xay-dung-quy-hoach" },
  { stt: 406, code: "1.014840.01", title: "Xác nhận công trình nhà ở không vi phạm hành lang an toàn lưới điện", type: "toan-trinh", group: "xay-dung-quy-hoach" },
  { stt: 407, code: "1.014845.01", title: "Cấp phép tạm thời công trình hạ tầng kỹ thuật nông thôn mới", type: "toan-trinh", group: "xay-dung-quy-hoach" },
  { stt: 408, code: "1.014850.01", title: "Công bố quy hoạch chi tiết xây dựng trung tâm xã", type: "toan-trinh", group: "xay-dung-quy-hoach" },
  { stt: 409, code: "1.014855.01", title: "Xác nhận nhà ở có đủ điều kiện an toàn chịu lực theo quy định", type: "toan-trinh", group: "xay-dung-quy-hoach" },
  { stt: 410, code: "1.014860.01", title: "Cấp Giấy chứng nhận nhà ở an toàn trước mùa bão lũ", type: "toan-trinh", group: "xay-dung-quy-hoach" },
  { stt: 411, code: "1.014865.01", title: "Cấp Giấy xác nhận tình trạng cư trú phục vụ giải quyết TTHC", type: "toan-trinh", group: "linh-vuc-khac" },
  { stt: 412, code: "1.014870.01", title: "Đăng ký tham gia Dịch vụ công trực tuyến mức độ Toàn trình trên VNeID", type: "toan-trinh", group: "linh-vuc-khac" },
  { stt: 413, code: "1.014875.01", title: "Tiếp nhận ý kiến đóng góp, kiến nghị của nhân dân qua Hòm thư điện tử", type: "toan-trinh", group: "linh-vuc-khac" },
  { stt: 414, code: "1.014880.01", title: "Đăng ký tiếp công dân định kỳ của Chủ tịch UBND xã", type: "toan-trinh", group: "linh-vuc-khac" },
  { stt: 415, code: "1.014885.01", title: "Cấp Giấy xác nhận quá trình công tác cán bộ không chuyên trách xã", type: "toan-trinh", group: "linh-vuc-khac" },
  { stt: 416, code: "1.014890.01", title: "Khen thưởng gia đình, cá nhân có thành tích xuất sắc trong phong trào xã", type: "toan-trinh", group: "linh-vuc-khac" },
  { stt: 417, code: "1.014895.01", title: "Xác nhận danh sách trúng tuyển nghĩa vụ quân sự hàng năm", type: "toan-trinh", group: "linh-vuc-khac" }
];


const groupMap = FIELD_GROUPS.reduce((acc, g) => {
  acc[g.id] = g.name;
  return acc;
}, {});

export const DAK_PXI_PROCEDURES_2026 = RAW_PROCEDURES_2026.map((p) => ({
  id: `dakpxi-${p.stt}`,
  stt: p.stt,
  code: p.code,
  slug: p.code.toLowerCase().replace(/[^a-z0-9]+/g, '-'),
  group_id: p.group,
  group_name: groupMap[p.group] || "Lĩnh vực khác",
  title: p.title,
  online_type: p.type,
  summary: `Thủ tục "${p.title}" theo quy định hành chính công năm 2026.`,
  processing_time: "Theo quy định hiện hành (01 - 05 ngày làm việc)",
  fee: "Theo quy định hiện hành / Miễn phí 100%",
  agency: "Cổng Dịch vụ công Quốc gia (dichvucong.gov.vn)",
  guideLink: `https://dichvucong.gov.vn/p/home/dvc-chi-tiet-thu-tuc-nganh.html?ma_thu_tuc=${encodeURIComponent(p.code)}`,
  view_count: p.stt === 3 ? 15420 : p.stt === 2 ? 14850 : p.stt === 7 ? 12300 : p.stt === 4 ? 11600 : p.stt === 5 ? 10950 : 500 + ((p.stt * 37) % 3500),
  required_documents: "Tờ khai điện tử theo mẫu; Giấy tờ tùy thân (CCCD/VNeID); Các tài liệu chuyên ngành liên quan.",
  conditions_text: "Công dân, tổ chức, hộ gia đình thụ hưởng dịch vụ trực tuyến.",
  steps: [
    { id: `step-${p.stt}-1`, title: "Nộp hồ sơ", content: "Nộp hồ sơ trực tuyến qua Cổng Dịch vụ công Quốc gia (dichvucong.gov.vn) bằng tài khoản VNeID (Mức 2)." },
    { id: `step-${p.stt}-2`, title: "Thụ lý hồ sơ", content: "Cán bộ chuyên môn kiểm tra tính hợp lệ của hồ sơ và thẩm định theo quy trình hành chính công." },
    { id: `step-${p.stt}-3`, title: "Trả kết quả", content: "Nhận kết quả điện tử trên ứng dụng VNeID/Cổng DVC hoặc dịch vụ Bưu chính." }
  ]
}));
